// Code generated by lexgen from generic.go; DO NOT EDIT.
//
// These are the generic scan cores (scanTokenG / scanPushG / errCheckG)
// monomorphized onto each concrete policy: the type parameters are erased and the
// policy is a concrete value, so the per-token p.emit / p.none / p.eof calls are
// direct and inline (no generics-dictionary indirection). Edit the generic cores
// in generic.go and re-run go generate; do not edit this file.

package lab

import (
	"errors"
	"io"

	codes "github.com/fredbi/core/json/lexers/error-codes"
	"github.com/fredbi/core/json/lexers/token"
)

// scanTokenSemantic is generated by lexgen from scanTokenG; DO NOT EDIT
// (edit scanTokenG in generic.go, then re-run go generate).
//
//nolint:gocognit,gocyclo
func scanTokenSemantic(l *L, p semanticPolicy) token.T {
	if l.err != nil {
		return p.none()
	}

	if l.trackBlanks {
		l.blanks = l.blanks[:0]
	}

	for {
		if err := l.readMore(); err != nil {
			return errCheckSemantic(l, p, err)
		}

		for l.consumed < l.bufferized {
			b := l.buffer[l.consumed]
			l.offset++
			l.consumed++

			switch b {
			case lineFeed:
				l.line++
				l.lineStart = l.offset
				if l.trackBlanks {
					l.blanks = append(l.blanks, b)
					if l.maxValueBytes > 0 && len(l.blanks) > l.maxValueBytes {
						// circuit breaker: also bound the verbatim whitespace buffer
						l.err = codes.ErrMaxValueBytes

						return p.none()
					}
				}

				continue

			case blank, tab, carriageReturn:
				if l.trackBlanks {
					l.blanks = append(l.blanks, b)
					if l.maxValueBytes > 0 && len(l.blanks) > l.maxValueBytes {
						// circuit breaker: also bound the verbatim whitespace buffer
						l.err = codes.ErrMaxValueBytes

						return p.none()
					}
				}

				continue
			}

			// a significant byte starts a token: snapshot its position
			l.tokLine = l.line
			l.tokCol = int(l.offset - l.lineStart)

			if l.afterKey {
				l.afterKey = false
				if b != colon {
					l.err = codes.ErrKeyColon

					return p.none()
				}

				l.current = token.MakeDelimiter(token.Colon)
				if l.elideSeparator {
					continue
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)
			}

			switch b {
			case colon:
				if l.current.Kind() == token.String {
					l.err = codes.ErrMissingObject
				} else {
					l.err = codes.ErrMissingKey
				}

				return p.none()

			case closingBracket:
				if l.current.IsComma() {
					l.err = codes.ErrTrailingComma

					return p.none()
				}
				if !l.isInObject() {
					l.err = codes.ErrNotInObject

					return p.none()
				}

				l.expectKey = false
				l.popContainer()
				l.current = token.MakeDelimiter(token.ClosingBracket)

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case closingSquareBracket:
				if l.current.IsComma() {
					l.err = codes.ErrTrailingComma

					return p.none()
				}
				if !l.isInArray() {
					l.err = codes.ErrNotInArray

					return p.none()
				}

				l.popContainer()
				l.current = token.MakeDelimiter(token.ClosingSquareBracket)

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case comma:
				if l.current.IsComma() {
					l.err = codes.ErrRepeatedComma

					return p.none()
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}
				if !l.isInContainer() {
					l.err = codes.ErrCommaInContainer

					return p.none()
				}
				if l.current.IsStartObject() || l.current.IsStartArray() || l.current.IsColon() {
					l.err = codes.ErrMissingValue

					return p.none()
				}

				if l.isInObject() {
					l.expectKey = true
				}

				l.current = token.MakeDelimiter(token.Comma)
				if l.elideSeparator {
					continue
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case openingBracket:
				if l.current.IsKnown() {
					if l.current.Kind() != token.Delimiter {
						l.err = codes.ErrInvalidToken

						return p.none()
					}
					if l.current.Delimiter().IsClosing() {
						l.err = codes.ErrMissingComma

						return p.none()
					}
					if l.isInArray() {
						if l.current.Delimiter() != token.OpeningSquareBracket &&
							l.current.Delimiter() != token.Comma {
							l.err = codes.ErrMissingComma

							return p.none()
						}
					} else if !l.current.IsColon() {
						l.err = codes.ErrMissingKey

						return p.none()
					}
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}

				l.expectKey = true
				l.pushObject()
				if l.err != nil {
					return p.none()
				}
				l.current = token.MakeDelimiter(token.OpeningBracket)

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case openingSquareBracket:
				if l.current.IsKnown() {
					if l.current.Kind() != token.Delimiter {
						l.err = codes.ErrInvalidToken

						return p.none()
					}
					if l.current.Delimiter().IsClosing() {
						l.err = codes.ErrMissingComma

						return p.none()
					}
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}

				l.pushArray()
				if l.err != nil {
					return p.none()
				}
				l.current = token.MakeDelimiter(token.OpeningSquareBracket)

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case doubleQuote:
				if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
					l.err = codes.ErrDelimitedValue
					l.current = token.None

					return p.none()
				}

				l.current = l.consumeString()
				if l.err != nil {
					return p.none()
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case startOfTrue, startOfFalse:
				if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
					l.err = codes.ErrDelimitedValue
					l.current = token.None

					return p.none()
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}

				l.current = l.consumeBoolean(b)
				if l.err != nil {
					return p.none()
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case minusSign, decimalPoint, '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
					l.err = codes.ErrDelimitedValue
					l.current = token.None

					return p.none()
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}

				if l.wholeBuffer && l.maxValueBytes == 0 {
					buf := l.buffer[:l.bufferized]
					numStart := l.consumed - 1
					runFrom := l.consumed
					var firstDigit byte
					ok := true

					switch {
					case b >= '0' && b <= '9':
						firstDigit = b
					case b == minusSign:
						if uint(l.consumed) < uint(len(buf)) && buf[l.consumed] >= '0' && buf[l.consumed] <= '9' {
							firstDigit = buf[l.consumed]
							runFrom = l.consumed + 1
						} else {
							ok = false
						}
					default:
						ok = false
					}

					if ok {
						n := runFrom
						for uint(n) < uint(len(buf)) && '0' <= buf[n] && buf[n] <= '9' {
							n++
						}

						leadingZero := firstDigit == '0' && n > runFrom
						var term byte
						if uint(n) < uint(len(buf)) {
							term = buf[n]
						}

						if !leadingZero && term != decimalPoint && term != 'e' && term != 'E' {
							l.offset += uint64(n - l.consumed)
							l.consumed = n
							l.current = token.MakeWithValue(token.Number, l.buffer[numStart:n:n])

							return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)
						}
					}

					l.current = l.consumeNumberWhole(b)
					if l.err != nil {
						return p.none()
					}

					return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)
				}

				l.current = l.consumeNumberStreaming(b)
				if l.err != nil {
					return p.none()
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case startOfNull:
				if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
					l.err = codes.ErrDelimitedValue
					l.current = token.None

					return p.none()
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}

				l.current = l.consumeNull(b)
				if l.err != nil {
					return p.none()
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			default:
				l.err = codes.ErrInvalidToken

				return p.none()
			}
		}
	}
}

// scanPushSemanticCore is generated by lexgen from scanPushG; DO NOT EDIT
// (edit scanPushG in generic.go, then re-run go generate).
//
//nolint:gocognit,gocyclo
func scanPushSemanticCore(l *L, p semanticPolicy, yield func(token.T) bool) {
	if l.err != nil {
		return
	}

	data := l.buffer[:l.bufferized]
	i := l.consumed
	// blankStart is the index right after the previous token: the whitespace run
	// [blankStart:tokenStart] is the preceding blanks the verbatim policy bakes
	// into the token (zero-copy slice of the input). The semantic policy ignores
	// it. It is reset to i after each emitted token.
	blankStart := i

	writeback := func(pos int) {
		l.consumed = pos
		l.offset = uint64(pos)
	}

	for i < len(data) {
		b := data[i]

		switch b {
		case lineFeed:
			i++
			l.line++
			l.lineStart = uint64(i)

			continue
		case blank, tab, carriageReturn:
			i++

			continue
		}

		l.tokLine = l.line
		l.tokCol = int(uint64(i+1) - l.lineStart)
		// the whitespace run since the previous token (zero-copy); i is the index
		// of the first significant byte (the token start).
		blanks := data[blankStart:i:i]

		if l.afterKey {
			l.afterKey = false
			if b != colon {
				l.err = codes.ErrKeyColon
				writeback(i + 1)

				return
			}

			i++
			l.current = token.MakeDelimiter(token.Colon)
			blankStart = i
			if l.elideSeparator {
				continue
			}
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

			continue
		}

		switch b {
		case colon:
			if l.current.Kind() == token.String {
				l.err = codes.ErrMissingObject
			} else {
				l.err = codes.ErrMissingKey
			}
			writeback(i + 1)

			return

		case closingBracket:
			if l.current.IsComma() {
				l.err = codes.ErrTrailingComma
				writeback(i + 1)

				return
			}
			if !l.isInObject() {
				l.err = codes.ErrNotInObject
				writeback(i + 1)

				return
			}

			i++
			l.expectKey = false
			l.popContainer()
			l.current = token.MakeDelimiter(token.ClosingBracket)
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

		case closingSquareBracket:
			if l.current.IsComma() {
				l.err = codes.ErrTrailingComma
				writeback(i + 1)

				return
			}
			if !l.isInArray() {
				l.err = codes.ErrNotInArray
				writeback(i + 1)

				return
			}

			i++
			l.popContainer()
			l.current = token.MakeDelimiter(token.ClosingSquareBracket)
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

		case comma:
			if l.current.IsComma() {
				l.err = codes.ErrRepeatedComma
				writeback(i + 1)

				return
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}
			if !l.isInContainer() {
				l.err = codes.ErrCommaInContainer
				writeback(i + 1)

				return
			}
			if l.current.IsStartObject() || l.current.IsStartArray() || l.current.IsColon() {
				l.err = codes.ErrMissingValue
				writeback(i + 1)

				return
			}

			if l.isInObject() {
				l.expectKey = true
			}

			i++
			l.current = token.MakeDelimiter(token.Comma)
			if l.elideSeparator {
				continue
			}
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

		case openingBracket:
			if l.current.IsKnown() {
				if l.current.Kind() != token.Delimiter {
					l.err = codes.ErrInvalidToken
					writeback(i + 1)

					return
				}
				if l.current.Delimiter().IsClosing() {
					l.err = codes.ErrMissingComma
					writeback(i + 1)

					return
				}
				if l.isInArray() {
					if l.current.Delimiter() != token.OpeningSquareBracket &&
						l.current.Delimiter() != token.Comma {
						l.err = codes.ErrMissingComma
						writeback(i + 1)

						return
					}
				} else if !l.current.IsColon() {
					l.err = codes.ErrMissingKey
					writeback(i + 1)

					return
				}
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}

			i++
			l.expectKey = true
			l.pushObject()
			if l.err != nil {
				writeback(i)

				return
			}
			l.current = token.MakeDelimiter(token.OpeningBracket)
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

		case openingSquareBracket:
			if l.current.IsKnown() {
				if l.current.Kind() != token.Delimiter {
					l.err = codes.ErrInvalidToken
					writeback(i + 1)

					return
				}
				if l.current.Delimiter().IsClosing() {
					l.err = codes.ErrMissingComma
					writeback(i + 1)

					return
				}
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}

			i++
			l.pushArray()
			if l.err != nil {
				writeback(i)

				return
			}
			l.current = token.MakeDelimiter(token.OpeningSquareBracket)
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

		case doubleQuote:
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return
			}

			writeback(i + 1)
			l.current = l.consumeString()
			if l.err != nil {
				return
			}
			i = l.consumed
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				return
			}

		case startOfTrue, startOfFalse:
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}

			writeback(i + 1)
			l.current = l.consumeBoolean(b)
			if l.err != nil {
				return
			}
			i = l.consumed
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				return
			}

		case minusSign, decimalPoint, '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}

			numStart := i
			runFrom := i + 1
			var firstDigit byte
			ok := true

			switch {
			case b >= '0' && b <= '9':
				firstDigit = b
			case b == minusSign:
				if uint(i+1) < uint(len(data)) && data[i+1] >= '0' && data[i+1] <= '9' {
					firstDigit = data[i+1]
					runFrom = i + 2
				} else {
					ok = false
				}
			default: // decimalPoint
				ok = false
			}

			if ok {
				n := runFrom
				for uint(n) < uint(len(data)) && '0' <= data[n] && data[n] <= '9' {
					n++
				}

				leadingZero := firstDigit == '0' && n > runFrom
				var term byte
				if uint(n) < uint(len(data)) {
					term = data[n]
				}

				if !leadingZero && term != decimalPoint && term != 'e' && term != 'E' {
					l.current = token.MakeWithValue(token.Number, data[numStart:n:n])
					i = n
					writeback(n)
					blankStart = i // this path continues, bypassing the loop-bottom update
					if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
						return
					}

					continue
				}
			}

			writeback(i + 1)
			l.current = l.consumeNumberWhole(b)
			if l.err != nil {
				return
			}
			i = l.consumed
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				return
			}

		case startOfNull:
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}

			writeback(i + 1)
			l.current = l.consumeNull(b)
			if l.err != nil {
				return
			}
			i = l.consumed
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				return
			}

		default:
			l.err = codes.ErrInvalidToken
			writeback(i + 1)

			return
		}

		// the token just processed ends at i: the next blanks run starts here.
		// (the afterKey colon path updates blankStart itself before its continue.)
		blankStart = i
	}

	writeback(i)
	// classify the terminal EOF for its side effects on l.err/l.isAtEOF; the
	// push core yields no token here, so the returned EOF token is discarded.
	_ = errCheckSemantic(l, p, io.EOF)
}

// errCheckSemantic is generated by lexgen from errCheckG; DO NOT EDIT
// (edit errCheckG in generic.go, then re-run go generate).
//
//nolint:gocognit,gocyclo
func errCheckSemantic(l *L, p semanticPolicy, err error) token.T {
	hadToken := l.current.IsKnown()
	l.current = token.None

	if errors.Is(err, io.EOF) {
		switch {
		case l.isInContainer():
			if l.isInObject() {
				l.err = codes.ErrNotInObject
			} else {
				l.err = codes.ErrNotInArray
			}
		case l.isAtEOF:
			l.err = io.EOF
		case !hadToken:
			l.err = codes.ErrNoData
		}

		l.isAtEOF = true

		return p.eof(l.blanks)
	}

	l.err = err

	return p.none()
}

// scanTokenVerbatim is generated by lexgen from scanTokenG; DO NOT EDIT
// (edit scanTokenG in generic.go, then re-run go generate).
//
//nolint:gocognit,gocyclo
func scanTokenVerbatim(l *L, p verbatimPolicy) token.VT {
	if l.err != nil {
		return p.none()
	}

	if l.trackBlanks {
		l.blanks = l.blanks[:0]
	}

	for {
		if err := l.readMore(); err != nil {
			return errCheckVerbatim(l, p, err)
		}

		for l.consumed < l.bufferized {
			b := l.buffer[l.consumed]
			l.offset++
			l.consumed++

			switch b {
			case lineFeed:
				l.line++
				l.lineStart = l.offset
				if l.trackBlanks {
					l.blanks = append(l.blanks, b)
					if l.maxValueBytes > 0 && len(l.blanks) > l.maxValueBytes {
						// circuit breaker: also bound the verbatim whitespace buffer
						l.err = codes.ErrMaxValueBytes

						return p.none()
					}
				}

				continue

			case blank, tab, carriageReturn:
				if l.trackBlanks {
					l.blanks = append(l.blanks, b)
					if l.maxValueBytes > 0 && len(l.blanks) > l.maxValueBytes {
						// circuit breaker: also bound the verbatim whitespace buffer
						l.err = codes.ErrMaxValueBytes

						return p.none()
					}
				}

				continue
			}

			// a significant byte starts a token: snapshot its position
			l.tokLine = l.line
			l.tokCol = int(l.offset - l.lineStart)

			if l.afterKey {
				l.afterKey = false
				if b != colon {
					l.err = codes.ErrKeyColon

					return p.none()
				}

				l.current = token.MakeDelimiter(token.Colon)
				if l.elideSeparator {
					continue
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)
			}

			switch b {
			case colon:
				if l.current.Kind() == token.String {
					l.err = codes.ErrMissingObject
				} else {
					l.err = codes.ErrMissingKey
				}

				return p.none()

			case closingBracket:
				if l.current.IsComma() {
					l.err = codes.ErrTrailingComma

					return p.none()
				}
				if !l.isInObject() {
					l.err = codes.ErrNotInObject

					return p.none()
				}

				l.expectKey = false
				l.popContainer()
				l.current = token.MakeDelimiter(token.ClosingBracket)

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case closingSquareBracket:
				if l.current.IsComma() {
					l.err = codes.ErrTrailingComma

					return p.none()
				}
				if !l.isInArray() {
					l.err = codes.ErrNotInArray

					return p.none()
				}

				l.popContainer()
				l.current = token.MakeDelimiter(token.ClosingSquareBracket)

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case comma:
				if l.current.IsComma() {
					l.err = codes.ErrRepeatedComma

					return p.none()
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}
				if !l.isInContainer() {
					l.err = codes.ErrCommaInContainer

					return p.none()
				}
				if l.current.IsStartObject() || l.current.IsStartArray() || l.current.IsColon() {
					l.err = codes.ErrMissingValue

					return p.none()
				}

				if l.isInObject() {
					l.expectKey = true
				}

				l.current = token.MakeDelimiter(token.Comma)
				if l.elideSeparator {
					continue
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case openingBracket:
				if l.current.IsKnown() {
					if l.current.Kind() != token.Delimiter {
						l.err = codes.ErrInvalidToken

						return p.none()
					}
					if l.current.Delimiter().IsClosing() {
						l.err = codes.ErrMissingComma

						return p.none()
					}
					if l.isInArray() {
						if l.current.Delimiter() != token.OpeningSquareBracket &&
							l.current.Delimiter() != token.Comma {
							l.err = codes.ErrMissingComma

							return p.none()
						}
					} else if !l.current.IsColon() {
						l.err = codes.ErrMissingKey

						return p.none()
					}
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}

				l.expectKey = true
				l.pushObject()
				if l.err != nil {
					return p.none()
				}
				l.current = token.MakeDelimiter(token.OpeningBracket)

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case openingSquareBracket:
				if l.current.IsKnown() {
					if l.current.Kind() != token.Delimiter {
						l.err = codes.ErrInvalidToken

						return p.none()
					}
					if l.current.Delimiter().IsClosing() {
						l.err = codes.ErrMissingComma

						return p.none()
					}
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}

				l.pushArray()
				if l.err != nil {
					return p.none()
				}
				l.current = token.MakeDelimiter(token.OpeningSquareBracket)

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case doubleQuote:
				if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
					l.err = codes.ErrDelimitedValue
					l.current = token.None

					return p.none()
				}

				l.current = l.consumeString()
				if l.err != nil {
					return p.none()
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case startOfTrue, startOfFalse:
				if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
					l.err = codes.ErrDelimitedValue
					l.current = token.None

					return p.none()
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}

				l.current = l.consumeBoolean(b)
				if l.err != nil {
					return p.none()
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case minusSign, decimalPoint, '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
					l.err = codes.ErrDelimitedValue
					l.current = token.None

					return p.none()
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}

				if l.wholeBuffer && l.maxValueBytes == 0 {
					buf := l.buffer[:l.bufferized]
					numStart := l.consumed - 1
					runFrom := l.consumed
					var firstDigit byte
					ok := true

					switch {
					case b >= '0' && b <= '9':
						firstDigit = b
					case b == minusSign:
						if uint(l.consumed) < uint(len(buf)) && buf[l.consumed] >= '0' && buf[l.consumed] <= '9' {
							firstDigit = buf[l.consumed]
							runFrom = l.consumed + 1
						} else {
							ok = false
						}
					default:
						ok = false
					}

					if ok {
						n := runFrom
						for uint(n) < uint(len(buf)) && '0' <= buf[n] && buf[n] <= '9' {
							n++
						}

						leadingZero := firstDigit == '0' && n > runFrom
						var term byte
						if uint(n) < uint(len(buf)) {
							term = buf[n]
						}

						if !leadingZero && term != decimalPoint && term != 'e' && term != 'E' {
							l.offset += uint64(n - l.consumed)
							l.consumed = n
							l.current = token.MakeWithValue(token.Number, l.buffer[numStart:n:n])

							return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)
						}
					}

					l.current = l.consumeNumberWhole(b)
					if l.err != nil {
						return p.none()
					}

					return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)
				}

				l.current = l.consumeNumberStreaming(b)
				if l.err != nil {
					return p.none()
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case startOfNull:
				if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
					l.err = codes.ErrDelimitedValue
					l.current = token.None

					return p.none()
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}

				l.current = l.consumeNull(b)
				if l.err != nil {
					return p.none()
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			default:
				l.err = codes.ErrInvalidToken

				return p.none()
			}
		}
	}
}

// scanPushVerbatimCore is generated by lexgen from scanPushG; DO NOT EDIT
// (edit scanPushG in generic.go, then re-run go generate).
//
//nolint:gocognit,gocyclo
func scanPushVerbatimCore(l *L, p verbatimPolicy, yield func(token.VT) bool) {
	if l.err != nil {
		return
	}

	data := l.buffer[:l.bufferized]
	i := l.consumed
	// blankStart is the index right after the previous token: the whitespace run
	// [blankStart:tokenStart] is the preceding blanks the verbatim policy bakes
	// into the token (zero-copy slice of the input). The semantic policy ignores
	// it. It is reset to i after each emitted token.
	blankStart := i

	writeback := func(pos int) {
		l.consumed = pos
		l.offset = uint64(pos)
	}

	for i < len(data) {
		b := data[i]

		switch b {
		case lineFeed:
			i++
			l.line++
			l.lineStart = uint64(i)

			continue
		case blank, tab, carriageReturn:
			i++

			continue
		}

		l.tokLine = l.line
		l.tokCol = int(uint64(i+1) - l.lineStart)
		// the whitespace run since the previous token (zero-copy); i is the index
		// of the first significant byte (the token start).
		blanks := data[blankStart:i:i]

		if l.afterKey {
			l.afterKey = false
			if b != colon {
				l.err = codes.ErrKeyColon
				writeback(i + 1)

				return
			}

			i++
			l.current = token.MakeDelimiter(token.Colon)
			blankStart = i
			if l.elideSeparator {
				continue
			}
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

			continue
		}

		switch b {
		case colon:
			if l.current.Kind() == token.String {
				l.err = codes.ErrMissingObject
			} else {
				l.err = codes.ErrMissingKey
			}
			writeback(i + 1)

			return

		case closingBracket:
			if l.current.IsComma() {
				l.err = codes.ErrTrailingComma
				writeback(i + 1)

				return
			}
			if !l.isInObject() {
				l.err = codes.ErrNotInObject
				writeback(i + 1)

				return
			}

			i++
			l.expectKey = false
			l.popContainer()
			l.current = token.MakeDelimiter(token.ClosingBracket)
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

		case closingSquareBracket:
			if l.current.IsComma() {
				l.err = codes.ErrTrailingComma
				writeback(i + 1)

				return
			}
			if !l.isInArray() {
				l.err = codes.ErrNotInArray
				writeback(i + 1)

				return
			}

			i++
			l.popContainer()
			l.current = token.MakeDelimiter(token.ClosingSquareBracket)
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

		case comma:
			if l.current.IsComma() {
				l.err = codes.ErrRepeatedComma
				writeback(i + 1)

				return
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}
			if !l.isInContainer() {
				l.err = codes.ErrCommaInContainer
				writeback(i + 1)

				return
			}
			if l.current.IsStartObject() || l.current.IsStartArray() || l.current.IsColon() {
				l.err = codes.ErrMissingValue
				writeback(i + 1)

				return
			}

			if l.isInObject() {
				l.expectKey = true
			}

			i++
			l.current = token.MakeDelimiter(token.Comma)
			if l.elideSeparator {
				continue
			}
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

		case openingBracket:
			if l.current.IsKnown() {
				if l.current.Kind() != token.Delimiter {
					l.err = codes.ErrInvalidToken
					writeback(i + 1)

					return
				}
				if l.current.Delimiter().IsClosing() {
					l.err = codes.ErrMissingComma
					writeback(i + 1)

					return
				}
				if l.isInArray() {
					if l.current.Delimiter() != token.OpeningSquareBracket &&
						l.current.Delimiter() != token.Comma {
						l.err = codes.ErrMissingComma
						writeback(i + 1)

						return
					}
				} else if !l.current.IsColon() {
					l.err = codes.ErrMissingKey
					writeback(i + 1)

					return
				}
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}

			i++
			l.expectKey = true
			l.pushObject()
			if l.err != nil {
				writeback(i)

				return
			}
			l.current = token.MakeDelimiter(token.OpeningBracket)
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

		case openingSquareBracket:
			if l.current.IsKnown() {
				if l.current.Kind() != token.Delimiter {
					l.err = codes.ErrInvalidToken
					writeback(i + 1)

					return
				}
				if l.current.Delimiter().IsClosing() {
					l.err = codes.ErrMissingComma
					writeback(i + 1)

					return
				}
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}

			i++
			l.pushArray()
			if l.err != nil {
				writeback(i)

				return
			}
			l.current = token.MakeDelimiter(token.OpeningSquareBracket)
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

		case doubleQuote:
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return
			}

			writeback(i + 1)
			l.current = l.consumeString()
			if l.err != nil {
				return
			}
			i = l.consumed
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				return
			}

		case startOfTrue, startOfFalse:
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}

			writeback(i + 1)
			l.current = l.consumeBoolean(b)
			if l.err != nil {
				return
			}
			i = l.consumed
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				return
			}

		case minusSign, decimalPoint, '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}

			numStart := i
			runFrom := i + 1
			var firstDigit byte
			ok := true

			switch {
			case b >= '0' && b <= '9':
				firstDigit = b
			case b == minusSign:
				if uint(i+1) < uint(len(data)) && data[i+1] >= '0' && data[i+1] <= '9' {
					firstDigit = data[i+1]
					runFrom = i + 2
				} else {
					ok = false
				}
			default: // decimalPoint
				ok = false
			}

			if ok {
				n := runFrom
				for uint(n) < uint(len(data)) && '0' <= data[n] && data[n] <= '9' {
					n++
				}

				leadingZero := firstDigit == '0' && n > runFrom
				var term byte
				if uint(n) < uint(len(data)) {
					term = data[n]
				}

				if !leadingZero && term != decimalPoint && term != 'e' && term != 'E' {
					l.current = token.MakeWithValue(token.Number, data[numStart:n:n])
					i = n
					writeback(n)
					blankStart = i // this path continues, bypassing the loop-bottom update
					if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
						return
					}

					continue
				}
			}

			writeback(i + 1)
			l.current = l.consumeNumberWhole(b)
			if l.err != nil {
				return
			}
			i = l.consumed
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				return
			}

		case startOfNull:
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}

			writeback(i + 1)
			l.current = l.consumeNull(b)
			if l.err != nil {
				return
			}
			i = l.consumed
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				return
			}

		default:
			l.err = codes.ErrInvalidToken
			writeback(i + 1)

			return
		}

		// the token just processed ends at i: the next blanks run starts here.
		// (the afterKey colon path updates blankStart itself before its continue.)
		blankStart = i
	}

	writeback(i)
	// classify the terminal EOF for its side effects on l.err/l.isAtEOF; the
	// push core yields no token here, so the returned EOF token is discarded.
	_ = errCheckVerbatim(l, p, io.EOF)
}

// errCheckVerbatim is generated by lexgen from errCheckG; DO NOT EDIT
// (edit errCheckG in generic.go, then re-run go generate).
//
//nolint:gocognit,gocyclo
func errCheckVerbatim(l *L, p verbatimPolicy, err error) token.VT {
	hadToken := l.current.IsKnown()
	l.current = token.None

	if errors.Is(err, io.EOF) {
		switch {
		case l.isInContainer():
			if l.isInObject() {
				l.err = codes.ErrNotInObject
			} else {
				l.err = codes.ErrNotInArray
			}
		case l.isAtEOF:
			l.err = io.EOF
		case !hadToken:
			l.err = codes.ErrNoData
		}

		l.isAtEOF = true

		return p.eof(l.blanks)
	}

	l.err = err

	return p.none()
}
