// Code generated by lexgen from generic.go; DO NOT EDIT.
//
// These are the generic scan cores (scanTokenG / scanPushG / errCheckG)
// monomorphized onto each concrete policy: the type parameters are erased and the
// policy is a concrete value, so the per-token p.emit / p.none / p.eof calls are
// direct and inline (no generics-dictionary indirection). Edit the generic cores
// in generic.go and re-run go generate; do not edit this file.

package lab

import (
	"errors"
	"io"

	codes "github.com/fredbi/core/json/lexers/error-codes"
	"github.com/fredbi/core/json/lexers/token"
)

// scanTokenBufferSemantic is generated by lexgen from scanTokenBufferG; DO NOT EDIT
// (edit scanTokenBufferG in generic.go, then re-run go generate).
//
//nolint:gocognit,gocyclo
func scanTokenBufferSemantic(l *L, p semanticPolicy) token.T {
	if l.err != nil {
		return p.none()
	}

	data := l.buffer[:l.bufferized]
	i := l.consumed
	// blankStart is the index right after the previous token: [blankStart:i] is the
	// whitespace run the verbatim policy bakes into the token (zero-copy). It is
	// only advanced past elided separators; every emit resets it via the next call's
	// re-init from l.consumed.
	blankStart := i

	writeback := func(pos int) {
		l.consumed = pos
		l.offset = uint64(pos)
	}

	for i < len(data) {
		b := data[i]

		switch b {
		case lineFeed:
			if !p.tracksPosition() {
				i += consumeWhitespace(data[i:]) // semantic batch-skip (citm bottleneck)

				continue
			}
			i++
			l.line++
			l.lineStart = uint64(i)

			continue
		case blank, tab, carriageReturn:
			if !p.tracksPosition() {
				i += consumeWhitespace(data[i:])

				continue
			}
			i++

			continue
		}

		if p.tracksPosition() {
			l.tokLine = l.line
			l.tokCol = int(uint64(i+1) - l.lineStart)
		}
		// the whitespace run since the previous token (zero-copy); i is the token start.
		blanks := data[blankStart:i:i]
		if p.storesBlanks() {
			l.blanks = blanks // state-based VL: stash the leading blanks in lexer state
		}

		// verbatim circuit breaker: bound the preceding-whitespace run. The stream
		// core checks this per-byte as it appends; here blanks is a zero-copy slice,
		// so one length check at the token boundary is equivalent (folded away in the
		// semantic core, where tracksPosition() is a false constant).
		if p.tracksPosition() && l.maxValueBytes > 0 && len(blanks) > l.maxValueBytes {
			l.err = codes.ErrMaxValueBytes
			writeback(i)

			return p.none()
		}

		if l.afterKey {
			l.afterKey = false
			if b != colon {
				l.err = codes.ErrKeyColon
				writeback(i + 1)

				return p.none()
			}

			i++
			l.current = token.MakeDelimiter(token.Colon)
			blankStart = i
			if l.elideSeparator {
				continue
			}
			writeback(i)

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)
		}

		switch b {
		case colon:
			if l.current.Kind() == token.String {
				l.err = codes.ErrMissingObject
			} else {
				l.err = codes.ErrMissingKey
			}
			writeback(i + 1)

			return p.none()

		case closingBracket:
			if l.current.IsComma() {
				l.err = codes.ErrTrailingComma
				writeback(i + 1)

				return p.none()
			}
			if !l.isInObject() {
				l.err = codes.ErrNotInObject
				writeback(i + 1)

				return p.none()
			}

			i++
			l.expectKey = false
			l.popContainer()
			l.current = token.MakeDelimiter(token.ClosingBracket)
			writeback(i)

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		case closingSquareBracket:
			if l.current.IsComma() {
				l.err = codes.ErrTrailingComma
				writeback(i + 1)

				return p.none()
			}
			if !l.isInArray() {
				l.err = codes.ErrNotInArray
				writeback(i + 1)

				return p.none()
			}

			i++
			l.popContainer()
			l.current = token.MakeDelimiter(token.ClosingSquareBracket)
			writeback(i)

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		case comma:
			if l.current.IsComma() {
				l.err = codes.ErrRepeatedComma
				writeback(i + 1)

				return p.none()
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return p.none()
			}
			if !l.isInContainer() {
				l.err = codes.ErrCommaInContainer
				writeback(i + 1)

				return p.none()
			}
			if l.current.IsStartObject() || l.current.IsStartArray() || l.current.IsColon() {
				l.err = codes.ErrMissingValue
				writeback(i + 1)

				return p.none()
			}

			if l.isInObject() {
				l.expectKey = true
			}

			i++
			l.current = token.MakeDelimiter(token.Comma)
			blankStart = i
			if l.elideSeparator {
				continue
			}
			writeback(i)

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		case openingBracket:
			if l.current.IsKnown() {
				if l.current.Kind() != token.Delimiter {
					l.err = codes.ErrInvalidToken
					writeback(i + 1)

					return p.none()
				}
				if l.current.Delimiter().IsClosing() {
					l.err = codes.ErrMissingComma
					writeback(i + 1)

					return p.none()
				}
				if l.isInArray() {
					if l.current.Delimiter() != token.OpeningSquareBracket &&
						l.current.Delimiter() != token.Comma {
						l.err = codes.ErrMissingComma
						writeback(i + 1)

						return p.none()
					}
				} else if !l.current.IsColon() {
					l.err = codes.ErrMissingKey
					writeback(i + 1)

					return p.none()
				}
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return p.none()
			}

			i++
			l.expectKey = true
			l.pushObject()
			if l.err != nil {
				writeback(i)

				return p.none()
			}
			l.current = token.MakeDelimiter(token.OpeningBracket)
			writeback(i)

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		case openingSquareBracket:
			if l.current.IsKnown() {
				if l.current.Kind() != token.Delimiter {
					l.err = codes.ErrInvalidToken
					writeback(i + 1)

					return p.none()
				}
				if l.current.Delimiter().IsClosing() {
					l.err = codes.ErrMissingComma
					writeback(i + 1)

					return p.none()
				}
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return p.none()
			}

			i++
			l.pushArray()
			if l.err != nil {
				writeback(i)

				return p.none()
			}
			l.current = token.MakeDelimiter(token.OpeningSquareBracket)
			writeback(i)

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		case doubleQuote:
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return p.none()
			}

			writeback(i + 1)
			l.current = l.consumeString()
			if l.err != nil {
				return p.none()
			}
			i = l.consumed

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		case startOfTrue, startOfFalse:
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return p.none()
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return p.none()
			}

			writeback(i + 1)
			l.current = l.consumeBoolean(b)
			if l.err != nil {
				return p.none()
			}
			i = l.consumed

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		case minusSign, decimalPoint, '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return p.none()
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return p.none()
			}

			// Bounded values (maxValueBytes) route to the streaming number consumer,
			// which enforces the cap; the inline fast path + consumeNumberWhole below
			// do not check it. In whole-buffer mode this gate reduces to maxValueBytes,
			// so the unbounded common case keeps the full inline fast path (§10 keeps
			// the champion shape; the old combined core gated it the same way).
			if l.maxValueBytes > 0 {
				writeback(i + 1)
				l.current = l.consumeNumberStreaming(b)
				if l.err != nil {
					return p.none()
				}
				i = l.consumed

				return p.emit(l.current, blanks, l.tokLine, l.tokCol)
			}

			numStart := i
			runFrom := i + 1
			var firstDigit byte
			ok := true

			switch {
			case b >= '0' && b <= '9':
				firstDigit = b
			case b == minusSign:
				if uint(i+1) < uint(len(data)) && data[i+1] >= '0' && data[i+1] <= '9' {
					firstDigit = data[i+1]
					runFrom = i + 2
				} else {
					ok = false
				}
			default: // decimalPoint
				ok = false
			}

			if ok {
				n := runFrom
				for uint(n) < uint(len(data)) && '0' <= data[n] && data[n] <= '9' {
					n++
				}

				leadingZero := firstDigit == '0' && n > runFrom
				end := n
				var term byte
				if uint(end) < uint(len(data)) {
					term = data[end]
				}
				// extend over a fractional part ('.' 1*DIGIT); a trailing dot leaves
				// term==decimalPoint for consumeNumberWhole's error.
				if !leadingZero && term == decimalPoint {
					m := end + 1
					for uint(m) < uint(len(data)) && '0' <= data[m] && data[m] <= '9' {
						m++
					}
					if m > end+1 { // at least one fractional digit
						end = m
						term = 0
						if uint(end) < uint(len(data)) {
							term = data[end]
						}
					}
				}
				// extend over an exponent ((e|E) [+|-] 1*DIGIT); cheaper than bailing to
				// consumeNumberWhole and re-scanning. A malformed exponent leaves
				// term=='e'/'E' for the slow-path error.
				if !leadingZero && (term == 'e' || term == 'E') {
					m := end + 1
					if uint(m) < uint(len(data)) && (data[m] == '+' || data[m] == '-') {
						m++
					}
					expStart := m
					for uint(m) < uint(len(data)) && '0' <= data[m] && data[m] <= '9' {
						m++
					}
					if m > expStart { // at least one exponent digit
						end = m
						term = 0
						if uint(end) < uint(len(data)) {
							term = data[end]
						}
					}
				}

				if !leadingZero && term != decimalPoint && term != 'e' && term != 'E' {
					l.current = token.MakeWithValue(token.Number, data[numStart:end:end])
					i = end
					writeback(end)

					return p.emit(l.current, blanks, l.tokLine, l.tokCol)
				}
			}

			writeback(i + 1)
			l.current = l.consumeNumberWhole(b)
			if l.err != nil {
				return p.none()
			}
			i = l.consumed

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		case startOfNull:
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return p.none()
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return p.none()
			}

			writeback(i + 1)
			l.current = l.consumeNull(b)
			if l.err != nil {
				return p.none()
			}
			i = l.consumed

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		default:
			l.err = codes.ErrInvalidToken
			writeback(i + 1)

			return p.none()
		}
	}

	// buffer exhausted: the trailing whitespace run [blankStart:i] is the verbatim
	// EOF token's preceding blanks (zero-copy); the semantic policy ignores it.
	l.blanks = data[blankStart:i:i]
	writeback(i)

	// verbatim circuit breaker on a trailing whitespace flood with no closing token
	// (parity with the stream core's per-byte check); folded away in the semantic core.
	if p.tracksPosition() && l.maxValueBytes > 0 && len(l.blanks) > l.maxValueBytes {
		l.err = codes.ErrMaxValueBytes

		return p.none()
	}

	return errCheckSemantic(l, p, io.EOF)
}

// scanTokenStreamSemantic is generated by lexgen from scanTokenStreamG; DO NOT EDIT
// (edit scanTokenStreamG in generic.go, then re-run go generate).
//
//nolint:gocognit,gocyclo
func scanTokenStreamSemantic(l *L, p semanticPolicy) token.T {
	if l.err != nil {
		return p.none()
	}

	if l.trackBlanks {
		l.blanks = l.blanks[:0]
	}

	for {
		if err := l.readMore(); err != nil {
			return errCheckSemantic(l, p, err)
		}

		for l.consumed < l.bufferized {
			b := l.buffer[l.consumed]
			l.offset++
			l.consumed++

			switch b {
			case lineFeed:
				if !p.tracksPosition() {
					// semantic: batch-skip the rest of the whitespace run with a local
					// cursor (no line/col, no blanks) — folds to the only path in the
					// devirtualized semantic core. This kills the per-byte struct-cursor
					// cost over whitespace (the citm bottleneck).
					ws := consumeWhitespace(l.buffer[l.consumed:l.bufferized])
					l.consumed += ws
					l.offset += uint64(ws)

					continue
				}
				// verbatim: track line + accumulate the blank run byte-by-byte
				l.line++
				l.lineStart = l.offset
				if l.trackBlanks {
					l.blanks = append(l.blanks, b)
					if l.maxValueBytes > 0 && len(l.blanks) > l.maxValueBytes {
						// circuit breaker: also bound the verbatim whitespace buffer
						l.err = codes.ErrMaxValueBytes

						return p.none()
					}
				}

				continue

			case blank, tab, carriageReturn:
				if !p.tracksPosition() {
					ws := consumeWhitespace(l.buffer[l.consumed:l.bufferized])
					l.consumed += ws
					l.offset += uint64(ws)

					continue
				}
				if l.trackBlanks {
					l.blanks = append(l.blanks, b)
					if l.maxValueBytes > 0 && len(l.blanks) > l.maxValueBytes {
						// circuit breaker: also bound the verbatim whitespace buffer
						l.err = codes.ErrMaxValueBytes

						return p.none()
					}
				}

				continue
			}

			// a significant byte starts a token: snapshot its position (verbatim only)
			if p.tracksPosition() {
				l.tokLine = l.line
				l.tokCol = int(l.offset - l.lineStart)
			}

			if l.afterKey {
				l.afterKey = false
				if b != colon {
					l.err = codes.ErrKeyColon

					return p.none()
				}

				l.current = token.MakeDelimiter(token.Colon)
				if l.elideSeparator {
					continue
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)
			}

			switch b {
			case colon:
				if l.current.Kind() == token.String {
					l.err = codes.ErrMissingObject
				} else {
					l.err = codes.ErrMissingKey
				}

				return p.none()

			case closingBracket:
				if l.current.IsComma() {
					l.err = codes.ErrTrailingComma

					return p.none()
				}
				if !l.isInObject() {
					l.err = codes.ErrNotInObject

					return p.none()
				}

				l.expectKey = false
				l.popContainer()
				l.current = token.MakeDelimiter(token.ClosingBracket)

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case closingSquareBracket:
				if l.current.IsComma() {
					l.err = codes.ErrTrailingComma

					return p.none()
				}
				if !l.isInArray() {
					l.err = codes.ErrNotInArray

					return p.none()
				}

				l.popContainer()
				l.current = token.MakeDelimiter(token.ClosingSquareBracket)

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case comma:
				if l.current.IsComma() {
					l.err = codes.ErrRepeatedComma

					return p.none()
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}
				if !l.isInContainer() {
					l.err = codes.ErrCommaInContainer

					return p.none()
				}
				if l.current.IsStartObject() || l.current.IsStartArray() || l.current.IsColon() {
					l.err = codes.ErrMissingValue

					return p.none()
				}

				if l.isInObject() {
					l.expectKey = true
				}

				l.current = token.MakeDelimiter(token.Comma)
				if l.elideSeparator {
					continue
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case openingBracket:
				if l.current.IsKnown() {
					if l.current.Kind() != token.Delimiter {
						l.err = codes.ErrInvalidToken

						return p.none()
					}
					if l.current.Delimiter().IsClosing() {
						l.err = codes.ErrMissingComma

						return p.none()
					}
					if l.isInArray() {
						if l.current.Delimiter() != token.OpeningSquareBracket &&
							l.current.Delimiter() != token.Comma {
							l.err = codes.ErrMissingComma

							return p.none()
						}
					} else if !l.current.IsColon() {
						l.err = codes.ErrMissingKey

						return p.none()
					}
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}

				l.expectKey = true
				l.pushObject()
				if l.err != nil {
					return p.none()
				}
				l.current = token.MakeDelimiter(token.OpeningBracket)

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case openingSquareBracket:
				if l.current.IsKnown() {
					if l.current.Kind() != token.Delimiter {
						l.err = codes.ErrInvalidToken

						return p.none()
					}
					if l.current.Delimiter().IsClosing() {
						l.err = codes.ErrMissingComma

						return p.none()
					}
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}

				l.pushArray()
				if l.err != nil {
					return p.none()
				}
				l.current = token.MakeDelimiter(token.OpeningSquareBracket)

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case doubleQuote:
				if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
					l.err = codes.ErrDelimitedValue
					l.current = token.None

					return p.none()
				}

				l.current = l.consumeString()
				if l.err != nil {
					return p.none()
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case startOfTrue, startOfFalse:
				if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
					l.err = codes.ErrDelimitedValue
					l.current = token.None

					return p.none()
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}

				l.current = l.consumeBoolean(b)
				if l.err != nil {
					return p.none()
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case minusSign, decimalPoint, '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
					l.err = codes.ErrDelimitedValue
					l.current = token.None

					return p.none()
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}

				l.current = l.consumeNumberStreamFast(b)
				if l.err != nil {
					return p.none()
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case startOfNull:
				if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
					l.err = codes.ErrDelimitedValue
					l.current = token.None

					return p.none()
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}

				l.current = l.consumeNull(b)
				if l.err != nil {
					return p.none()
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			default:
				l.err = codes.ErrInvalidToken

				return p.none()
			}
		}
	}
}

// scanPushSemanticCore is generated by lexgen from scanPushG; DO NOT EDIT
// (edit scanPushG in generic.go, then re-run go generate).
//
//nolint:gocognit,gocyclo
func scanPushSemanticCore(l *L, p semanticPolicy, yield func(token.T) bool) {
	if l.err != nil {
		return
	}

	data := l.buffer[:l.bufferized]
	i := l.consumed
	// blankStart is the index right after the previous token: the whitespace run
	// [blankStart:tokenStart] is the preceding blanks the verbatim policy bakes
	// into the token (zero-copy slice of the input). The semantic policy ignores
	// it. It is reset to i after each emitted token.
	blankStart := i

	writeback := func(pos int) {
		l.consumed = pos
		l.offset = uint64(pos)
	}

	for i < len(data) {
		b := data[i]

		switch b {
		case lineFeed:
			if !p.tracksPosition() {
				// semantic: batch-skip the whole whitespace run in one shot (the
				// citm/indentation bottleneck), mirroring the pull core. Gated by
				// the compile-time tracksPosition() constant so the verbatim core,
				// which must walk each blank to accumulate the preceding-blanks
				// slice and count lines, keeps its per-byte path below. Register-
				// safe: the semantic core has headroom since it dropped line/col.
				i += consumeWhitespace(data[i:])

				continue
			}
			i++
			l.line++
			l.lineStart = uint64(i)

			continue
		case blank, tab, carriageReturn:
			if !p.tracksPosition() {
				i += consumeWhitespace(data[i:]) // semantic batch-skip; see lineFeed

				continue
			}
			i++

			continue
		}

		if p.tracksPosition() {
			l.tokLine = l.line
			l.tokCol = int(uint64(i+1) - l.lineStart)
		}
		// the whitespace run since the previous token (zero-copy); i is the index
		// of the first significant byte (the token start).
		blanks := data[blankStart:i:i]
		if p.storesBlanks() {
			l.blanks = blanks // state-based VL: stash the leading blanks in lexer state
		}

		if l.afterKey {
			l.afterKey = false
			if b != colon {
				l.err = codes.ErrKeyColon
				writeback(i + 1)

				return
			}

			i++
			l.current = token.MakeDelimiter(token.Colon)
			blankStart = i
			if l.elideSeparator {
				continue
			}
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

			continue
		}

		switch b {
		case colon:
			if l.current.Kind() == token.String {
				l.err = codes.ErrMissingObject
			} else {
				l.err = codes.ErrMissingKey
			}
			writeback(i + 1)

			return

		case closingBracket:
			if l.current.IsComma() {
				l.err = codes.ErrTrailingComma
				writeback(i + 1)

				return
			}
			if !l.isInObject() {
				l.err = codes.ErrNotInObject
				writeback(i + 1)

				return
			}

			i++
			l.expectKey = false
			l.popContainer()
			l.current = token.MakeDelimiter(token.ClosingBracket)
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

		case closingSquareBracket:
			if l.current.IsComma() {
				l.err = codes.ErrTrailingComma
				writeback(i + 1)

				return
			}
			if !l.isInArray() {
				l.err = codes.ErrNotInArray
				writeback(i + 1)

				return
			}

			i++
			l.popContainer()
			l.current = token.MakeDelimiter(token.ClosingSquareBracket)
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

		case comma:
			if l.current.IsComma() {
				l.err = codes.ErrRepeatedComma
				writeback(i + 1)

				return
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}
			if !l.isInContainer() {
				l.err = codes.ErrCommaInContainer
				writeback(i + 1)

				return
			}
			if l.current.IsStartObject() || l.current.IsStartArray() || l.current.IsColon() {
				l.err = codes.ErrMissingValue
				writeback(i + 1)

				return
			}

			if l.isInObject() {
				l.expectKey = true
			}

			i++
			l.current = token.MakeDelimiter(token.Comma)
			if l.elideSeparator {
				continue
			}
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

		case openingBracket:
			if l.current.IsKnown() {
				if l.current.Kind() != token.Delimiter {
					l.err = codes.ErrInvalidToken
					writeback(i + 1)

					return
				}
				if l.current.Delimiter().IsClosing() {
					l.err = codes.ErrMissingComma
					writeback(i + 1)

					return
				}
				if l.isInArray() {
					if l.current.Delimiter() != token.OpeningSquareBracket &&
						l.current.Delimiter() != token.Comma {
						l.err = codes.ErrMissingComma
						writeback(i + 1)

						return
					}
				} else if !l.current.IsColon() {
					l.err = codes.ErrMissingKey
					writeback(i + 1)

					return
				}
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}

			i++
			l.expectKey = true
			l.pushObject()
			if l.err != nil {
				writeback(i)

				return
			}
			l.current = token.MakeDelimiter(token.OpeningBracket)
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

		case openingSquareBracket:
			if l.current.IsKnown() {
				if l.current.Kind() != token.Delimiter {
					l.err = codes.ErrInvalidToken
					writeback(i + 1)

					return
				}
				if l.current.Delimiter().IsClosing() {
					l.err = codes.ErrMissingComma
					writeback(i + 1)

					return
				}
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}

			i++
			l.pushArray()
			if l.err != nil {
				writeback(i)

				return
			}
			l.current = token.MakeDelimiter(token.OpeningSquareBracket)
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

		case doubleQuote:
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return
			}

			writeback(i + 1)
			l.current = l.consumeString()
			if l.err != nil {
				return
			}
			i = l.consumed
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				return
			}

		case startOfTrue, startOfFalse:
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}

			writeback(i + 1)
			l.current = l.consumeBoolean(b)
			if l.err != nil {
				return
			}
			i = l.consumed
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				return
			}

		case minusSign, decimalPoint, '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}

			numStart := i
			runFrom := i + 1
			var firstDigit byte
			ok := true

			switch {
			case b >= '0' && b <= '9':
				firstDigit = b
			case b == minusSign:
				if uint(i+1) < uint(len(data)) && data[i+1] >= '0' && data[i+1] <= '9' {
					firstDigit = data[i+1]
					runFrom = i + 2
				} else {
					ok = false
				}
			default: // decimalPoint
				ok = false
			}

			if ok {
				n := runFrom
				for uint(n) < uint(len(data)) && '0' <= data[n] && data[n] <= '9' {
					n++
				}

				leadingZero := firstDigit == '0' && n > runFrom
				end := n
				var term byte
				if uint(end) < uint(len(data)) {
					term = data[end]
				}
				// extend the fast path over a fractional part ('.' 1*DIGIT). A
				// trailing dot (no fraction digit) leaves term==decimalPoint, which the
				// final guard routes to consumeNumberWhole for the right error.
				if !leadingZero && term == decimalPoint {
					m := end + 1
					for uint(m) < uint(len(data)) && '0' <= data[m] && data[m] <= '9' {
						m++
					}
					if m > end+1 { // at least one fractional digit
						end = m
						term = 0
						if uint(end) < uint(len(data)) {
							term = data[end]
						}
					}
				}
				// extend over an exponent ((e|E) [+|-] 1*DIGIT). Completing it inline
				// is cheaper than bailing to consumeNumberWhole, which would re-scan
				// the int+frac we already consumed. A malformed exponent leaves
				// term=='e'/'E' and routes to the slow path for the right error.
				if !leadingZero && (term == 'e' || term == 'E') {
					m := end + 1
					if uint(m) < uint(len(data)) && (data[m] == '+' || data[m] == '-') {
						m++
					}
					expStart := m
					for uint(m) < uint(len(data)) && '0' <= data[m] && data[m] <= '9' {
						m++
					}
					if m > expStart { // at least one exponent digit
						end = m
						term = 0
						if uint(end) < uint(len(data)) {
							term = data[end]
						}
					}
				}

				if !leadingZero && term != decimalPoint && term != 'e' && term != 'E' {
					l.current = token.MakeWithValue(token.Number, data[numStart:end:end])
					i = end
					writeback(end)
					blankStart = i // this path continues, bypassing the loop-bottom update
					if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
						return
					}

					continue
				}
			}

			writeback(i + 1)
			l.current = l.consumeNumberWhole(b)
			if l.err != nil {
				return
			}
			i = l.consumed
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				return
			}

		case startOfNull:
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}

			writeback(i + 1)
			l.current = l.consumeNull(b)
			if l.err != nil {
				return
			}
			i = l.consumed
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				return
			}

		default:
			l.err = codes.ErrInvalidToken
			writeback(i + 1)

			return
		}

		// the token just processed ends at i: the next blanks run starts here.
		// (the afterKey colon path updates blankStart itself before its continue.)
		blankStart = i
	}

	writeback(i)
	// classify the terminal EOF for its side effects on l.err/l.isAtEOF; the
	// push core yields no token here, so the returned EOF token is discarded.
	_ = errCheckSemantic(l, p, io.EOF)
}

// errCheckSemantic is generated by lexgen from errCheckG; DO NOT EDIT
// (edit errCheckG in generic.go, then re-run go generate).
//
//nolint:gocognit,gocyclo
func errCheckSemantic(l *L, p semanticPolicy, err error) token.T {
	hadToken := l.current.IsKnown()
	l.current = token.None

	if errors.Is(err, io.EOF) {
		switch {
		case l.isInContainer():
			if l.isInObject() {
				l.err = codes.ErrNotInObject
			} else {
				l.err = codes.ErrNotInArray
			}
		case l.isAtEOF:
			l.err = io.EOF
		case !hadToken:
			l.err = codes.ErrNoData
		}

		l.isAtEOF = true

		return p.eof(l.blanks)
	}

	l.err = err

	return p.none()
}

// scanTokenBufferVerbatim is generated by lexgen from scanTokenBufferG; DO NOT EDIT
// (edit scanTokenBufferG in generic.go, then re-run go generate).
//
//nolint:gocognit,gocyclo
func scanTokenBufferVerbatim(l *L, p verbatimPolicy) token.VT {
	if l.err != nil {
		return p.none()
	}

	data := l.buffer[:l.bufferized]
	i := l.consumed
	// blankStart is the index right after the previous token: [blankStart:i] is the
	// whitespace run the verbatim policy bakes into the token (zero-copy). It is
	// only advanced past elided separators; every emit resets it via the next call's
	// re-init from l.consumed.
	blankStart := i

	writeback := func(pos int) {
		l.consumed = pos
		l.offset = uint64(pos)
	}

	for i < len(data) {
		b := data[i]

		switch b {
		case lineFeed:
			if !p.tracksPosition() {
				i += consumeWhitespace(data[i:]) // semantic batch-skip (citm bottleneck)

				continue
			}
			i++
			l.line++
			l.lineStart = uint64(i)

			continue
		case blank, tab, carriageReturn:
			if !p.tracksPosition() {
				i += consumeWhitespace(data[i:])

				continue
			}
			i++

			continue
		}

		if p.tracksPosition() {
			l.tokLine = l.line
			l.tokCol = int(uint64(i+1) - l.lineStart)
		}
		// the whitespace run since the previous token (zero-copy); i is the token start.
		blanks := data[blankStart:i:i]
		if p.storesBlanks() {
			l.blanks = blanks // state-based VL: stash the leading blanks in lexer state
		}

		// verbatim circuit breaker: bound the preceding-whitespace run. The stream
		// core checks this per-byte as it appends; here blanks is a zero-copy slice,
		// so one length check at the token boundary is equivalent (folded away in the
		// semantic core, where tracksPosition() is a false constant).
		if p.tracksPosition() && l.maxValueBytes > 0 && len(blanks) > l.maxValueBytes {
			l.err = codes.ErrMaxValueBytes
			writeback(i)

			return p.none()
		}

		if l.afterKey {
			l.afterKey = false
			if b != colon {
				l.err = codes.ErrKeyColon
				writeback(i + 1)

				return p.none()
			}

			i++
			l.current = token.MakeDelimiter(token.Colon)
			blankStart = i
			if l.elideSeparator {
				continue
			}
			writeback(i)

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)
		}

		switch b {
		case colon:
			if l.current.Kind() == token.String {
				l.err = codes.ErrMissingObject
			} else {
				l.err = codes.ErrMissingKey
			}
			writeback(i + 1)

			return p.none()

		case closingBracket:
			if l.current.IsComma() {
				l.err = codes.ErrTrailingComma
				writeback(i + 1)

				return p.none()
			}
			if !l.isInObject() {
				l.err = codes.ErrNotInObject
				writeback(i + 1)

				return p.none()
			}

			i++
			l.expectKey = false
			l.popContainer()
			l.current = token.MakeDelimiter(token.ClosingBracket)
			writeback(i)

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		case closingSquareBracket:
			if l.current.IsComma() {
				l.err = codes.ErrTrailingComma
				writeback(i + 1)

				return p.none()
			}
			if !l.isInArray() {
				l.err = codes.ErrNotInArray
				writeback(i + 1)

				return p.none()
			}

			i++
			l.popContainer()
			l.current = token.MakeDelimiter(token.ClosingSquareBracket)
			writeback(i)

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		case comma:
			if l.current.IsComma() {
				l.err = codes.ErrRepeatedComma
				writeback(i + 1)

				return p.none()
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return p.none()
			}
			if !l.isInContainer() {
				l.err = codes.ErrCommaInContainer
				writeback(i + 1)

				return p.none()
			}
			if l.current.IsStartObject() || l.current.IsStartArray() || l.current.IsColon() {
				l.err = codes.ErrMissingValue
				writeback(i + 1)

				return p.none()
			}

			if l.isInObject() {
				l.expectKey = true
			}

			i++
			l.current = token.MakeDelimiter(token.Comma)
			blankStart = i
			if l.elideSeparator {
				continue
			}
			writeback(i)

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		case openingBracket:
			if l.current.IsKnown() {
				if l.current.Kind() != token.Delimiter {
					l.err = codes.ErrInvalidToken
					writeback(i + 1)

					return p.none()
				}
				if l.current.Delimiter().IsClosing() {
					l.err = codes.ErrMissingComma
					writeback(i + 1)

					return p.none()
				}
				if l.isInArray() {
					if l.current.Delimiter() != token.OpeningSquareBracket &&
						l.current.Delimiter() != token.Comma {
						l.err = codes.ErrMissingComma
						writeback(i + 1)

						return p.none()
					}
				} else if !l.current.IsColon() {
					l.err = codes.ErrMissingKey
					writeback(i + 1)

					return p.none()
				}
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return p.none()
			}

			i++
			l.expectKey = true
			l.pushObject()
			if l.err != nil {
				writeback(i)

				return p.none()
			}
			l.current = token.MakeDelimiter(token.OpeningBracket)
			writeback(i)

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		case openingSquareBracket:
			if l.current.IsKnown() {
				if l.current.Kind() != token.Delimiter {
					l.err = codes.ErrInvalidToken
					writeback(i + 1)

					return p.none()
				}
				if l.current.Delimiter().IsClosing() {
					l.err = codes.ErrMissingComma
					writeback(i + 1)

					return p.none()
				}
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return p.none()
			}

			i++
			l.pushArray()
			if l.err != nil {
				writeback(i)

				return p.none()
			}
			l.current = token.MakeDelimiter(token.OpeningSquareBracket)
			writeback(i)

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		case doubleQuote:
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return p.none()
			}

			writeback(i + 1)
			l.current = l.consumeString()
			if l.err != nil {
				return p.none()
			}
			i = l.consumed

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		case startOfTrue, startOfFalse:
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return p.none()
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return p.none()
			}

			writeback(i + 1)
			l.current = l.consumeBoolean(b)
			if l.err != nil {
				return p.none()
			}
			i = l.consumed

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		case minusSign, decimalPoint, '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return p.none()
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return p.none()
			}

			// Bounded values (maxValueBytes) route to the streaming number consumer,
			// which enforces the cap; the inline fast path + consumeNumberWhole below
			// do not check it. In whole-buffer mode this gate reduces to maxValueBytes,
			// so the unbounded common case keeps the full inline fast path (§10 keeps
			// the champion shape; the old combined core gated it the same way).
			if l.maxValueBytes > 0 {
				writeback(i + 1)
				l.current = l.consumeNumberStreaming(b)
				if l.err != nil {
					return p.none()
				}
				i = l.consumed

				return p.emit(l.current, blanks, l.tokLine, l.tokCol)
			}

			numStart := i
			runFrom := i + 1
			var firstDigit byte
			ok := true

			switch {
			case b >= '0' && b <= '9':
				firstDigit = b
			case b == minusSign:
				if uint(i+1) < uint(len(data)) && data[i+1] >= '0' && data[i+1] <= '9' {
					firstDigit = data[i+1]
					runFrom = i + 2
				} else {
					ok = false
				}
			default: // decimalPoint
				ok = false
			}

			if ok {
				n := runFrom
				for uint(n) < uint(len(data)) && '0' <= data[n] && data[n] <= '9' {
					n++
				}

				leadingZero := firstDigit == '0' && n > runFrom
				end := n
				var term byte
				if uint(end) < uint(len(data)) {
					term = data[end]
				}
				// extend over a fractional part ('.' 1*DIGIT); a trailing dot leaves
				// term==decimalPoint for consumeNumberWhole's error.
				if !leadingZero && term == decimalPoint {
					m := end + 1
					for uint(m) < uint(len(data)) && '0' <= data[m] && data[m] <= '9' {
						m++
					}
					if m > end+1 { // at least one fractional digit
						end = m
						term = 0
						if uint(end) < uint(len(data)) {
							term = data[end]
						}
					}
				}
				// extend over an exponent ((e|E) [+|-] 1*DIGIT); cheaper than bailing to
				// consumeNumberWhole and re-scanning. A malformed exponent leaves
				// term=='e'/'E' for the slow-path error.
				if !leadingZero && (term == 'e' || term == 'E') {
					m := end + 1
					if uint(m) < uint(len(data)) && (data[m] == '+' || data[m] == '-') {
						m++
					}
					expStart := m
					for uint(m) < uint(len(data)) && '0' <= data[m] && data[m] <= '9' {
						m++
					}
					if m > expStart { // at least one exponent digit
						end = m
						term = 0
						if uint(end) < uint(len(data)) {
							term = data[end]
						}
					}
				}

				if !leadingZero && term != decimalPoint && term != 'e' && term != 'E' {
					l.current = token.MakeWithValue(token.Number, data[numStart:end:end])
					i = end
					writeback(end)

					return p.emit(l.current, blanks, l.tokLine, l.tokCol)
				}
			}

			writeback(i + 1)
			l.current = l.consumeNumberWhole(b)
			if l.err != nil {
				return p.none()
			}
			i = l.consumed

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		case startOfNull:
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return p.none()
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return p.none()
			}

			writeback(i + 1)
			l.current = l.consumeNull(b)
			if l.err != nil {
				return p.none()
			}
			i = l.consumed

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		default:
			l.err = codes.ErrInvalidToken
			writeback(i + 1)

			return p.none()
		}
	}

	// buffer exhausted: the trailing whitespace run [blankStart:i] is the verbatim
	// EOF token's preceding blanks (zero-copy); the semantic policy ignores it.
	l.blanks = data[blankStart:i:i]
	writeback(i)

	// verbatim circuit breaker on a trailing whitespace flood with no closing token
	// (parity with the stream core's per-byte check); folded away in the semantic core.
	if p.tracksPosition() && l.maxValueBytes > 0 && len(l.blanks) > l.maxValueBytes {
		l.err = codes.ErrMaxValueBytes

		return p.none()
	}

	return errCheckVerbatim(l, p, io.EOF)
}

// scanTokenStreamVerbatim is generated by lexgen from scanTokenStreamG; DO NOT EDIT
// (edit scanTokenStreamG in generic.go, then re-run go generate).
//
//nolint:gocognit,gocyclo
func scanTokenStreamVerbatim(l *L, p verbatimPolicy) token.VT {
	if l.err != nil {
		return p.none()
	}

	if l.trackBlanks {
		l.blanks = l.blanks[:0]
	}

	for {
		if err := l.readMore(); err != nil {
			return errCheckVerbatim(l, p, err)
		}

		for l.consumed < l.bufferized {
			b := l.buffer[l.consumed]
			l.offset++
			l.consumed++

			switch b {
			case lineFeed:
				if !p.tracksPosition() {
					// semantic: batch-skip the rest of the whitespace run with a local
					// cursor (no line/col, no blanks) — folds to the only path in the
					// devirtualized semantic core. This kills the per-byte struct-cursor
					// cost over whitespace (the citm bottleneck).
					ws := consumeWhitespace(l.buffer[l.consumed:l.bufferized])
					l.consumed += ws
					l.offset += uint64(ws)

					continue
				}
				// verbatim: track line + accumulate the blank run byte-by-byte
				l.line++
				l.lineStart = l.offset
				if l.trackBlanks {
					l.blanks = append(l.blanks, b)
					if l.maxValueBytes > 0 && len(l.blanks) > l.maxValueBytes {
						// circuit breaker: also bound the verbatim whitespace buffer
						l.err = codes.ErrMaxValueBytes

						return p.none()
					}
				}

				continue

			case blank, tab, carriageReturn:
				if !p.tracksPosition() {
					ws := consumeWhitespace(l.buffer[l.consumed:l.bufferized])
					l.consumed += ws
					l.offset += uint64(ws)

					continue
				}
				if l.trackBlanks {
					l.blanks = append(l.blanks, b)
					if l.maxValueBytes > 0 && len(l.blanks) > l.maxValueBytes {
						// circuit breaker: also bound the verbatim whitespace buffer
						l.err = codes.ErrMaxValueBytes

						return p.none()
					}
				}

				continue
			}

			// a significant byte starts a token: snapshot its position (verbatim only)
			if p.tracksPosition() {
				l.tokLine = l.line
				l.tokCol = int(l.offset - l.lineStart)
			}

			if l.afterKey {
				l.afterKey = false
				if b != colon {
					l.err = codes.ErrKeyColon

					return p.none()
				}

				l.current = token.MakeDelimiter(token.Colon)
				if l.elideSeparator {
					continue
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)
			}

			switch b {
			case colon:
				if l.current.Kind() == token.String {
					l.err = codes.ErrMissingObject
				} else {
					l.err = codes.ErrMissingKey
				}

				return p.none()

			case closingBracket:
				if l.current.IsComma() {
					l.err = codes.ErrTrailingComma

					return p.none()
				}
				if !l.isInObject() {
					l.err = codes.ErrNotInObject

					return p.none()
				}

				l.expectKey = false
				l.popContainer()
				l.current = token.MakeDelimiter(token.ClosingBracket)

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case closingSquareBracket:
				if l.current.IsComma() {
					l.err = codes.ErrTrailingComma

					return p.none()
				}
				if !l.isInArray() {
					l.err = codes.ErrNotInArray

					return p.none()
				}

				l.popContainer()
				l.current = token.MakeDelimiter(token.ClosingSquareBracket)

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case comma:
				if l.current.IsComma() {
					l.err = codes.ErrRepeatedComma

					return p.none()
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}
				if !l.isInContainer() {
					l.err = codes.ErrCommaInContainer

					return p.none()
				}
				if l.current.IsStartObject() || l.current.IsStartArray() || l.current.IsColon() {
					l.err = codes.ErrMissingValue

					return p.none()
				}

				if l.isInObject() {
					l.expectKey = true
				}

				l.current = token.MakeDelimiter(token.Comma)
				if l.elideSeparator {
					continue
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case openingBracket:
				if l.current.IsKnown() {
					if l.current.Kind() != token.Delimiter {
						l.err = codes.ErrInvalidToken

						return p.none()
					}
					if l.current.Delimiter().IsClosing() {
						l.err = codes.ErrMissingComma

						return p.none()
					}
					if l.isInArray() {
						if l.current.Delimiter() != token.OpeningSquareBracket &&
							l.current.Delimiter() != token.Comma {
							l.err = codes.ErrMissingComma

							return p.none()
						}
					} else if !l.current.IsColon() {
						l.err = codes.ErrMissingKey

						return p.none()
					}
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}

				l.expectKey = true
				l.pushObject()
				if l.err != nil {
					return p.none()
				}
				l.current = token.MakeDelimiter(token.OpeningBracket)

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case openingSquareBracket:
				if l.current.IsKnown() {
					if l.current.Kind() != token.Delimiter {
						l.err = codes.ErrInvalidToken

						return p.none()
					}
					if l.current.Delimiter().IsClosing() {
						l.err = codes.ErrMissingComma

						return p.none()
					}
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}

				l.pushArray()
				if l.err != nil {
					return p.none()
				}
				l.current = token.MakeDelimiter(token.OpeningSquareBracket)

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case doubleQuote:
				if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
					l.err = codes.ErrDelimitedValue
					l.current = token.None

					return p.none()
				}

				l.current = l.consumeString()
				if l.err != nil {
					return p.none()
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case startOfTrue, startOfFalse:
				if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
					l.err = codes.ErrDelimitedValue
					l.current = token.None

					return p.none()
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}

				l.current = l.consumeBoolean(b)
				if l.err != nil {
					return p.none()
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case minusSign, decimalPoint, '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
					l.err = codes.ErrDelimitedValue
					l.current = token.None

					return p.none()
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}

				l.current = l.consumeNumberStreamFast(b)
				if l.err != nil {
					return p.none()
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case startOfNull:
				if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
					l.err = codes.ErrDelimitedValue
					l.current = token.None

					return p.none()
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}

				l.current = l.consumeNull(b)
				if l.err != nil {
					return p.none()
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			default:
				l.err = codes.ErrInvalidToken

				return p.none()
			}
		}
	}
}

// scanPushVerbatimCore is generated by lexgen from scanPushG; DO NOT EDIT
// (edit scanPushG in generic.go, then re-run go generate).
//
//nolint:gocognit,gocyclo
func scanPushVerbatimCore(l *L, p verbatimPolicy, yield func(token.VT) bool) {
	if l.err != nil {
		return
	}

	data := l.buffer[:l.bufferized]
	i := l.consumed
	// blankStart is the index right after the previous token: the whitespace run
	// [blankStart:tokenStart] is the preceding blanks the verbatim policy bakes
	// into the token (zero-copy slice of the input). The semantic policy ignores
	// it. It is reset to i after each emitted token.
	blankStart := i

	writeback := func(pos int) {
		l.consumed = pos
		l.offset = uint64(pos)
	}

	for i < len(data) {
		b := data[i]

		switch b {
		case lineFeed:
			if !p.tracksPosition() {
				// semantic: batch-skip the whole whitespace run in one shot (the
				// citm/indentation bottleneck), mirroring the pull core. Gated by
				// the compile-time tracksPosition() constant so the verbatim core,
				// which must walk each blank to accumulate the preceding-blanks
				// slice and count lines, keeps its per-byte path below. Register-
				// safe: the semantic core has headroom since it dropped line/col.
				i += consumeWhitespace(data[i:])

				continue
			}
			i++
			l.line++
			l.lineStart = uint64(i)

			continue
		case blank, tab, carriageReturn:
			if !p.tracksPosition() {
				i += consumeWhitespace(data[i:]) // semantic batch-skip; see lineFeed

				continue
			}
			i++

			continue
		}

		if p.tracksPosition() {
			l.tokLine = l.line
			l.tokCol = int(uint64(i+1) - l.lineStart)
		}
		// the whitespace run since the previous token (zero-copy); i is the index
		// of the first significant byte (the token start).
		blanks := data[blankStart:i:i]
		if p.storesBlanks() {
			l.blanks = blanks // state-based VL: stash the leading blanks in lexer state
		}

		if l.afterKey {
			l.afterKey = false
			if b != colon {
				l.err = codes.ErrKeyColon
				writeback(i + 1)

				return
			}

			i++
			l.current = token.MakeDelimiter(token.Colon)
			blankStart = i
			if l.elideSeparator {
				continue
			}
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

			continue
		}

		switch b {
		case colon:
			if l.current.Kind() == token.String {
				l.err = codes.ErrMissingObject
			} else {
				l.err = codes.ErrMissingKey
			}
			writeback(i + 1)

			return

		case closingBracket:
			if l.current.IsComma() {
				l.err = codes.ErrTrailingComma
				writeback(i + 1)

				return
			}
			if !l.isInObject() {
				l.err = codes.ErrNotInObject
				writeback(i + 1)

				return
			}

			i++
			l.expectKey = false
			l.popContainer()
			l.current = token.MakeDelimiter(token.ClosingBracket)
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

		case closingSquareBracket:
			if l.current.IsComma() {
				l.err = codes.ErrTrailingComma
				writeback(i + 1)

				return
			}
			if !l.isInArray() {
				l.err = codes.ErrNotInArray
				writeback(i + 1)

				return
			}

			i++
			l.popContainer()
			l.current = token.MakeDelimiter(token.ClosingSquareBracket)
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

		case comma:
			if l.current.IsComma() {
				l.err = codes.ErrRepeatedComma
				writeback(i + 1)

				return
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}
			if !l.isInContainer() {
				l.err = codes.ErrCommaInContainer
				writeback(i + 1)

				return
			}
			if l.current.IsStartObject() || l.current.IsStartArray() || l.current.IsColon() {
				l.err = codes.ErrMissingValue
				writeback(i + 1)

				return
			}

			if l.isInObject() {
				l.expectKey = true
			}

			i++
			l.current = token.MakeDelimiter(token.Comma)
			if l.elideSeparator {
				continue
			}
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

		case openingBracket:
			if l.current.IsKnown() {
				if l.current.Kind() != token.Delimiter {
					l.err = codes.ErrInvalidToken
					writeback(i + 1)

					return
				}
				if l.current.Delimiter().IsClosing() {
					l.err = codes.ErrMissingComma
					writeback(i + 1)

					return
				}
				if l.isInArray() {
					if l.current.Delimiter() != token.OpeningSquareBracket &&
						l.current.Delimiter() != token.Comma {
						l.err = codes.ErrMissingComma
						writeback(i + 1)

						return
					}
				} else if !l.current.IsColon() {
					l.err = codes.ErrMissingKey
					writeback(i + 1)

					return
				}
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}

			i++
			l.expectKey = true
			l.pushObject()
			if l.err != nil {
				writeback(i)

				return
			}
			l.current = token.MakeDelimiter(token.OpeningBracket)
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

		case openingSquareBracket:
			if l.current.IsKnown() {
				if l.current.Kind() != token.Delimiter {
					l.err = codes.ErrInvalidToken
					writeback(i + 1)

					return
				}
				if l.current.Delimiter().IsClosing() {
					l.err = codes.ErrMissingComma
					writeback(i + 1)

					return
				}
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}

			i++
			l.pushArray()
			if l.err != nil {
				writeback(i)

				return
			}
			l.current = token.MakeDelimiter(token.OpeningSquareBracket)
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

		case doubleQuote:
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return
			}

			writeback(i + 1)
			l.current = l.consumeString()
			if l.err != nil {
				return
			}
			i = l.consumed
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				return
			}

		case startOfTrue, startOfFalse:
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}

			writeback(i + 1)
			l.current = l.consumeBoolean(b)
			if l.err != nil {
				return
			}
			i = l.consumed
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				return
			}

		case minusSign, decimalPoint, '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}

			numStart := i
			runFrom := i + 1
			var firstDigit byte
			ok := true

			switch {
			case b >= '0' && b <= '9':
				firstDigit = b
			case b == minusSign:
				if uint(i+1) < uint(len(data)) && data[i+1] >= '0' && data[i+1] <= '9' {
					firstDigit = data[i+1]
					runFrom = i + 2
				} else {
					ok = false
				}
			default: // decimalPoint
				ok = false
			}

			if ok {
				n := runFrom
				for uint(n) < uint(len(data)) && '0' <= data[n] && data[n] <= '9' {
					n++
				}

				leadingZero := firstDigit == '0' && n > runFrom
				end := n
				var term byte
				if uint(end) < uint(len(data)) {
					term = data[end]
				}
				// extend the fast path over a fractional part ('.' 1*DIGIT). A
				// trailing dot (no fraction digit) leaves term==decimalPoint, which the
				// final guard routes to consumeNumberWhole for the right error.
				if !leadingZero && term == decimalPoint {
					m := end + 1
					for uint(m) < uint(len(data)) && '0' <= data[m] && data[m] <= '9' {
						m++
					}
					if m > end+1 { // at least one fractional digit
						end = m
						term = 0
						if uint(end) < uint(len(data)) {
							term = data[end]
						}
					}
				}
				// extend over an exponent ((e|E) [+|-] 1*DIGIT). Completing it inline
				// is cheaper than bailing to consumeNumberWhole, which would re-scan
				// the int+frac we already consumed. A malformed exponent leaves
				// term=='e'/'E' and routes to the slow path for the right error.
				if !leadingZero && (term == 'e' || term == 'E') {
					m := end + 1
					if uint(m) < uint(len(data)) && (data[m] == '+' || data[m] == '-') {
						m++
					}
					expStart := m
					for uint(m) < uint(len(data)) && '0' <= data[m] && data[m] <= '9' {
						m++
					}
					if m > expStart { // at least one exponent digit
						end = m
						term = 0
						if uint(end) < uint(len(data)) {
							term = data[end]
						}
					}
				}

				if !leadingZero && term != decimalPoint && term != 'e' && term != 'E' {
					l.current = token.MakeWithValue(token.Number, data[numStart:end:end])
					i = end
					writeback(end)
					blankStart = i // this path continues, bypassing the loop-bottom update
					if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
						return
					}

					continue
				}
			}

			writeback(i + 1)
			l.current = l.consumeNumberWhole(b)
			if l.err != nil {
				return
			}
			i = l.consumed
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				return
			}

		case startOfNull:
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}

			writeback(i + 1)
			l.current = l.consumeNull(b)
			if l.err != nil {
				return
			}
			i = l.consumed
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				return
			}

		default:
			l.err = codes.ErrInvalidToken
			writeback(i + 1)

			return
		}

		// the token just processed ends at i: the next blanks run starts here.
		// (the afterKey colon path updates blankStart itself before its continue.)
		blankStart = i
	}

	writeback(i)
	// classify the terminal EOF for its side effects on l.err/l.isAtEOF; the
	// push core yields no token here, so the returned EOF token is discarded.
	_ = errCheckVerbatim(l, p, io.EOF)
}

// errCheckVerbatim is generated by lexgen from errCheckG; DO NOT EDIT
// (edit errCheckG in generic.go, then re-run go generate).
//
//nolint:gocognit,gocyclo
func errCheckVerbatim(l *L, p verbatimPolicy, err error) token.VT {
	hadToken := l.current.IsKnown()
	l.current = token.None

	if errors.Is(err, io.EOF) {
		switch {
		case l.isInContainer():
			if l.isInObject() {
				l.err = codes.ErrNotInObject
			} else {
				l.err = codes.ErrNotInArray
			}
		case l.isAtEOF:
			l.err = io.EOF
		case !hadToken:
			l.err = codes.ErrNoData
		}

		l.isAtEOF = true

		return p.eof(l.blanks)
	}

	l.err = err

	return p.none()
}

// scanTokenBufferState is generated by lexgen from scanTokenBufferG; DO NOT EDIT
// (edit scanTokenBufferG in generic.go, then re-run go generate).
//
//nolint:gocognit,gocyclo
func scanTokenBufferState(l *L, p statePolicy) token.T {
	if l.err != nil {
		return p.none()
	}

	data := l.buffer[:l.bufferized]
	i := l.consumed
	// blankStart is the index right after the previous token: [blankStart:i] is the
	// whitespace run the verbatim policy bakes into the token (zero-copy). It is
	// only advanced past elided separators; every emit resets it via the next call's
	// re-init from l.consumed.
	blankStart := i

	writeback := func(pos int) {
		l.consumed = pos
		l.offset = uint64(pos)
	}

	for i < len(data) {
		b := data[i]

		switch b {
		case lineFeed:
			if !p.tracksPosition() {
				i += consumeWhitespace(data[i:]) // semantic batch-skip (citm bottleneck)

				continue
			}
			i++
			l.line++
			l.lineStart = uint64(i)

			continue
		case blank, tab, carriageReturn:
			if !p.tracksPosition() {
				i += consumeWhitespace(data[i:])

				continue
			}
			i++

			continue
		}

		if p.tracksPosition() {
			l.tokLine = l.line
			l.tokCol = int(uint64(i+1) - l.lineStart)
		}
		// the whitespace run since the previous token (zero-copy); i is the token start.
		blanks := data[blankStart:i:i]
		if p.storesBlanks() {
			l.blanks = blanks // state-based VL: stash the leading blanks in lexer state
		}

		// verbatim circuit breaker: bound the preceding-whitespace run. The stream
		// core checks this per-byte as it appends; here blanks is a zero-copy slice,
		// so one length check at the token boundary is equivalent (folded away in the
		// semantic core, where tracksPosition() is a false constant).
		if p.tracksPosition() && l.maxValueBytes > 0 && len(blanks) > l.maxValueBytes {
			l.err = codes.ErrMaxValueBytes
			writeback(i)

			return p.none()
		}

		if l.afterKey {
			l.afterKey = false
			if b != colon {
				l.err = codes.ErrKeyColon
				writeback(i + 1)

				return p.none()
			}

			i++
			l.current = token.MakeDelimiter(token.Colon)
			blankStart = i
			if l.elideSeparator {
				continue
			}
			writeback(i)

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)
		}

		switch b {
		case colon:
			if l.current.Kind() == token.String {
				l.err = codes.ErrMissingObject
			} else {
				l.err = codes.ErrMissingKey
			}
			writeback(i + 1)

			return p.none()

		case closingBracket:
			if l.current.IsComma() {
				l.err = codes.ErrTrailingComma
				writeback(i + 1)

				return p.none()
			}
			if !l.isInObject() {
				l.err = codes.ErrNotInObject
				writeback(i + 1)

				return p.none()
			}

			i++
			l.expectKey = false
			l.popContainer()
			l.current = token.MakeDelimiter(token.ClosingBracket)
			writeback(i)

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		case closingSquareBracket:
			if l.current.IsComma() {
				l.err = codes.ErrTrailingComma
				writeback(i + 1)

				return p.none()
			}
			if !l.isInArray() {
				l.err = codes.ErrNotInArray
				writeback(i + 1)

				return p.none()
			}

			i++
			l.popContainer()
			l.current = token.MakeDelimiter(token.ClosingSquareBracket)
			writeback(i)

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		case comma:
			if l.current.IsComma() {
				l.err = codes.ErrRepeatedComma
				writeback(i + 1)

				return p.none()
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return p.none()
			}
			if !l.isInContainer() {
				l.err = codes.ErrCommaInContainer
				writeback(i + 1)

				return p.none()
			}
			if l.current.IsStartObject() || l.current.IsStartArray() || l.current.IsColon() {
				l.err = codes.ErrMissingValue
				writeback(i + 1)

				return p.none()
			}

			if l.isInObject() {
				l.expectKey = true
			}

			i++
			l.current = token.MakeDelimiter(token.Comma)
			blankStart = i
			if l.elideSeparator {
				continue
			}
			writeback(i)

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		case openingBracket:
			if l.current.IsKnown() {
				if l.current.Kind() != token.Delimiter {
					l.err = codes.ErrInvalidToken
					writeback(i + 1)

					return p.none()
				}
				if l.current.Delimiter().IsClosing() {
					l.err = codes.ErrMissingComma
					writeback(i + 1)

					return p.none()
				}
				if l.isInArray() {
					if l.current.Delimiter() != token.OpeningSquareBracket &&
						l.current.Delimiter() != token.Comma {
						l.err = codes.ErrMissingComma
						writeback(i + 1)

						return p.none()
					}
				} else if !l.current.IsColon() {
					l.err = codes.ErrMissingKey
					writeback(i + 1)

					return p.none()
				}
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return p.none()
			}

			i++
			l.expectKey = true
			l.pushObject()
			if l.err != nil {
				writeback(i)

				return p.none()
			}
			l.current = token.MakeDelimiter(token.OpeningBracket)
			writeback(i)

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		case openingSquareBracket:
			if l.current.IsKnown() {
				if l.current.Kind() != token.Delimiter {
					l.err = codes.ErrInvalidToken
					writeback(i + 1)

					return p.none()
				}
				if l.current.Delimiter().IsClosing() {
					l.err = codes.ErrMissingComma
					writeback(i + 1)

					return p.none()
				}
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return p.none()
			}

			i++
			l.pushArray()
			if l.err != nil {
				writeback(i)

				return p.none()
			}
			l.current = token.MakeDelimiter(token.OpeningSquareBracket)
			writeback(i)

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		case doubleQuote:
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return p.none()
			}

			writeback(i + 1)
			l.current = l.consumeString()
			if l.err != nil {
				return p.none()
			}
			i = l.consumed

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		case startOfTrue, startOfFalse:
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return p.none()
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return p.none()
			}

			writeback(i + 1)
			l.current = l.consumeBoolean(b)
			if l.err != nil {
				return p.none()
			}
			i = l.consumed

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		case minusSign, decimalPoint, '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return p.none()
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return p.none()
			}

			// Bounded values (maxValueBytes) route to the streaming number consumer,
			// which enforces the cap; the inline fast path + consumeNumberWhole below
			// do not check it. In whole-buffer mode this gate reduces to maxValueBytes,
			// so the unbounded common case keeps the full inline fast path (§10 keeps
			// the champion shape; the old combined core gated it the same way).
			if l.maxValueBytes > 0 {
				writeback(i + 1)
				l.current = l.consumeNumberStreaming(b)
				if l.err != nil {
					return p.none()
				}
				i = l.consumed

				return p.emit(l.current, blanks, l.tokLine, l.tokCol)
			}

			numStart := i
			runFrom := i + 1
			var firstDigit byte
			ok := true

			switch {
			case b >= '0' && b <= '9':
				firstDigit = b
			case b == minusSign:
				if uint(i+1) < uint(len(data)) && data[i+1] >= '0' && data[i+1] <= '9' {
					firstDigit = data[i+1]
					runFrom = i + 2
				} else {
					ok = false
				}
			default: // decimalPoint
				ok = false
			}

			if ok {
				n := runFrom
				for uint(n) < uint(len(data)) && '0' <= data[n] && data[n] <= '9' {
					n++
				}

				leadingZero := firstDigit == '0' && n > runFrom
				end := n
				var term byte
				if uint(end) < uint(len(data)) {
					term = data[end]
				}
				// extend over a fractional part ('.' 1*DIGIT); a trailing dot leaves
				// term==decimalPoint for consumeNumberWhole's error.
				if !leadingZero && term == decimalPoint {
					m := end + 1
					for uint(m) < uint(len(data)) && '0' <= data[m] && data[m] <= '9' {
						m++
					}
					if m > end+1 { // at least one fractional digit
						end = m
						term = 0
						if uint(end) < uint(len(data)) {
							term = data[end]
						}
					}
				}
				// extend over an exponent ((e|E) [+|-] 1*DIGIT); cheaper than bailing to
				// consumeNumberWhole and re-scanning. A malformed exponent leaves
				// term=='e'/'E' for the slow-path error.
				if !leadingZero && (term == 'e' || term == 'E') {
					m := end + 1
					if uint(m) < uint(len(data)) && (data[m] == '+' || data[m] == '-') {
						m++
					}
					expStart := m
					for uint(m) < uint(len(data)) && '0' <= data[m] && data[m] <= '9' {
						m++
					}
					if m > expStart { // at least one exponent digit
						end = m
						term = 0
						if uint(end) < uint(len(data)) {
							term = data[end]
						}
					}
				}

				if !leadingZero && term != decimalPoint && term != 'e' && term != 'E' {
					l.current = token.MakeWithValue(token.Number, data[numStart:end:end])
					i = end
					writeback(end)

					return p.emit(l.current, blanks, l.tokLine, l.tokCol)
				}
			}

			writeback(i + 1)
			l.current = l.consumeNumberWhole(b)
			if l.err != nil {
				return p.none()
			}
			i = l.consumed

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		case startOfNull:
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return p.none()
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return p.none()
			}

			writeback(i + 1)
			l.current = l.consumeNull(b)
			if l.err != nil {
				return p.none()
			}
			i = l.consumed

			return p.emit(l.current, blanks, l.tokLine, l.tokCol)

		default:
			l.err = codes.ErrInvalidToken
			writeback(i + 1)

			return p.none()
		}
	}

	// buffer exhausted: the trailing whitespace run [blankStart:i] is the verbatim
	// EOF token's preceding blanks (zero-copy); the semantic policy ignores it.
	l.blanks = data[blankStart:i:i]
	writeback(i)

	// verbatim circuit breaker on a trailing whitespace flood with no closing token
	// (parity with the stream core's per-byte check); folded away in the semantic core.
	if p.tracksPosition() && l.maxValueBytes > 0 && len(l.blanks) > l.maxValueBytes {
		l.err = codes.ErrMaxValueBytes

		return p.none()
	}

	return errCheckState(l, p, io.EOF)
}

// scanTokenStreamState is generated by lexgen from scanTokenStreamG; DO NOT EDIT
// (edit scanTokenStreamG in generic.go, then re-run go generate).
//
//nolint:gocognit,gocyclo
func scanTokenStreamState(l *L, p statePolicy) token.T {
	if l.err != nil {
		return p.none()
	}

	if l.trackBlanks {
		l.blanks = l.blanks[:0]
	}

	for {
		if err := l.readMore(); err != nil {
			return errCheckState(l, p, err)
		}

		for l.consumed < l.bufferized {
			b := l.buffer[l.consumed]
			l.offset++
			l.consumed++

			switch b {
			case lineFeed:
				if !p.tracksPosition() {
					// semantic: batch-skip the rest of the whitespace run with a local
					// cursor (no line/col, no blanks) — folds to the only path in the
					// devirtualized semantic core. This kills the per-byte struct-cursor
					// cost over whitespace (the citm bottleneck).
					ws := consumeWhitespace(l.buffer[l.consumed:l.bufferized])
					l.consumed += ws
					l.offset += uint64(ws)

					continue
				}
				// verbatim: track line + accumulate the blank run byte-by-byte
				l.line++
				l.lineStart = l.offset
				if l.trackBlanks {
					l.blanks = append(l.blanks, b)
					if l.maxValueBytes > 0 && len(l.blanks) > l.maxValueBytes {
						// circuit breaker: also bound the verbatim whitespace buffer
						l.err = codes.ErrMaxValueBytes

						return p.none()
					}
				}

				continue

			case blank, tab, carriageReturn:
				if !p.tracksPosition() {
					ws := consumeWhitespace(l.buffer[l.consumed:l.bufferized])
					l.consumed += ws
					l.offset += uint64(ws)

					continue
				}
				if l.trackBlanks {
					l.blanks = append(l.blanks, b)
					if l.maxValueBytes > 0 && len(l.blanks) > l.maxValueBytes {
						// circuit breaker: also bound the verbatim whitespace buffer
						l.err = codes.ErrMaxValueBytes

						return p.none()
					}
				}

				continue
			}

			// a significant byte starts a token: snapshot its position (verbatim only)
			if p.tracksPosition() {
				l.tokLine = l.line
				l.tokCol = int(l.offset - l.lineStart)
			}

			if l.afterKey {
				l.afterKey = false
				if b != colon {
					l.err = codes.ErrKeyColon

					return p.none()
				}

				l.current = token.MakeDelimiter(token.Colon)
				if l.elideSeparator {
					continue
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)
			}

			switch b {
			case colon:
				if l.current.Kind() == token.String {
					l.err = codes.ErrMissingObject
				} else {
					l.err = codes.ErrMissingKey
				}

				return p.none()

			case closingBracket:
				if l.current.IsComma() {
					l.err = codes.ErrTrailingComma

					return p.none()
				}
				if !l.isInObject() {
					l.err = codes.ErrNotInObject

					return p.none()
				}

				l.expectKey = false
				l.popContainer()
				l.current = token.MakeDelimiter(token.ClosingBracket)

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case closingSquareBracket:
				if l.current.IsComma() {
					l.err = codes.ErrTrailingComma

					return p.none()
				}
				if !l.isInArray() {
					l.err = codes.ErrNotInArray

					return p.none()
				}

				l.popContainer()
				l.current = token.MakeDelimiter(token.ClosingSquareBracket)

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case comma:
				if l.current.IsComma() {
					l.err = codes.ErrRepeatedComma

					return p.none()
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}
				if !l.isInContainer() {
					l.err = codes.ErrCommaInContainer

					return p.none()
				}
				if l.current.IsStartObject() || l.current.IsStartArray() || l.current.IsColon() {
					l.err = codes.ErrMissingValue

					return p.none()
				}

				if l.isInObject() {
					l.expectKey = true
				}

				l.current = token.MakeDelimiter(token.Comma)
				if l.elideSeparator {
					continue
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case openingBracket:
				if l.current.IsKnown() {
					if l.current.Kind() != token.Delimiter {
						l.err = codes.ErrInvalidToken

						return p.none()
					}
					if l.current.Delimiter().IsClosing() {
						l.err = codes.ErrMissingComma

						return p.none()
					}
					if l.isInArray() {
						if l.current.Delimiter() != token.OpeningSquareBracket &&
							l.current.Delimiter() != token.Comma {
							l.err = codes.ErrMissingComma

							return p.none()
						}
					} else if !l.current.IsColon() {
						l.err = codes.ErrMissingKey

						return p.none()
					}
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}

				l.expectKey = true
				l.pushObject()
				if l.err != nil {
					return p.none()
				}
				l.current = token.MakeDelimiter(token.OpeningBracket)

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case openingSquareBracket:
				if l.current.IsKnown() {
					if l.current.Kind() != token.Delimiter {
						l.err = codes.ErrInvalidToken

						return p.none()
					}
					if l.current.Delimiter().IsClosing() {
						l.err = codes.ErrMissingComma

						return p.none()
					}
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}

				l.pushArray()
				if l.err != nil {
					return p.none()
				}
				l.current = token.MakeDelimiter(token.OpeningSquareBracket)

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case doubleQuote:
				if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
					l.err = codes.ErrDelimitedValue
					l.current = token.None

					return p.none()
				}

				l.current = l.consumeString()
				if l.err != nil {
					return p.none()
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case startOfTrue, startOfFalse:
				if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
					l.err = codes.ErrDelimitedValue
					l.current = token.None

					return p.none()
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}

				l.current = l.consumeBoolean(b)
				if l.err != nil {
					return p.none()
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case minusSign, decimalPoint, '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
					l.err = codes.ErrDelimitedValue
					l.current = token.None

					return p.none()
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}

				l.current = l.consumeNumberStreamFast(b)
				if l.err != nil {
					return p.none()
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			case startOfNull:
				if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
					l.err = codes.ErrDelimitedValue
					l.current = token.None

					return p.none()
				}
				if l.expectKey {
					l.err = codes.ErrMissingKey

					return p.none()
				}

				l.current = l.consumeNull(b)
				if l.err != nil {
					return p.none()
				}

				return p.emit(l.current, l.blanks, l.tokLine, l.tokCol)

			default:
				l.err = codes.ErrInvalidToken

				return p.none()
			}
		}
	}
}

// scanPushStateCore is generated by lexgen from scanPushG; DO NOT EDIT
// (edit scanPushG in generic.go, then re-run go generate).
//
//nolint:gocognit,gocyclo
func scanPushStateCore(l *L, p statePolicy, yield func(token.T) bool) {
	if l.err != nil {
		return
	}

	data := l.buffer[:l.bufferized]
	i := l.consumed
	// blankStart is the index right after the previous token: the whitespace run
	// [blankStart:tokenStart] is the preceding blanks the verbatim policy bakes
	// into the token (zero-copy slice of the input). The semantic policy ignores
	// it. It is reset to i after each emitted token.
	blankStart := i

	writeback := func(pos int) {
		l.consumed = pos
		l.offset = uint64(pos)
	}

	for i < len(data) {
		b := data[i]

		switch b {
		case lineFeed:
			if !p.tracksPosition() {
				// semantic: batch-skip the whole whitespace run in one shot (the
				// citm/indentation bottleneck), mirroring the pull core. Gated by
				// the compile-time tracksPosition() constant so the verbatim core,
				// which must walk each blank to accumulate the preceding-blanks
				// slice and count lines, keeps its per-byte path below. Register-
				// safe: the semantic core has headroom since it dropped line/col.
				i += consumeWhitespace(data[i:])

				continue
			}
			i++
			l.line++
			l.lineStart = uint64(i)

			continue
		case blank, tab, carriageReturn:
			if !p.tracksPosition() {
				i += consumeWhitespace(data[i:]) // semantic batch-skip; see lineFeed

				continue
			}
			i++

			continue
		}

		if p.tracksPosition() {
			l.tokLine = l.line
			l.tokCol = int(uint64(i+1) - l.lineStart)
		}
		// the whitespace run since the previous token (zero-copy); i is the index
		// of the first significant byte (the token start).
		blanks := data[blankStart:i:i]
		if p.storesBlanks() {
			l.blanks = blanks // state-based VL: stash the leading blanks in lexer state
		}

		if l.afterKey {
			l.afterKey = false
			if b != colon {
				l.err = codes.ErrKeyColon
				writeback(i + 1)

				return
			}

			i++
			l.current = token.MakeDelimiter(token.Colon)
			blankStart = i
			if l.elideSeparator {
				continue
			}
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

			continue
		}

		switch b {
		case colon:
			if l.current.Kind() == token.String {
				l.err = codes.ErrMissingObject
			} else {
				l.err = codes.ErrMissingKey
			}
			writeback(i + 1)

			return

		case closingBracket:
			if l.current.IsComma() {
				l.err = codes.ErrTrailingComma
				writeback(i + 1)

				return
			}
			if !l.isInObject() {
				l.err = codes.ErrNotInObject
				writeback(i + 1)

				return
			}

			i++
			l.expectKey = false
			l.popContainer()
			l.current = token.MakeDelimiter(token.ClosingBracket)
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

		case closingSquareBracket:
			if l.current.IsComma() {
				l.err = codes.ErrTrailingComma
				writeback(i + 1)

				return
			}
			if !l.isInArray() {
				l.err = codes.ErrNotInArray
				writeback(i + 1)

				return
			}

			i++
			l.popContainer()
			l.current = token.MakeDelimiter(token.ClosingSquareBracket)
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

		case comma:
			if l.current.IsComma() {
				l.err = codes.ErrRepeatedComma
				writeback(i + 1)

				return
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}
			if !l.isInContainer() {
				l.err = codes.ErrCommaInContainer
				writeback(i + 1)

				return
			}
			if l.current.IsStartObject() || l.current.IsStartArray() || l.current.IsColon() {
				l.err = codes.ErrMissingValue
				writeback(i + 1)

				return
			}

			if l.isInObject() {
				l.expectKey = true
			}

			i++
			l.current = token.MakeDelimiter(token.Comma)
			if l.elideSeparator {
				continue
			}
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

		case openingBracket:
			if l.current.IsKnown() {
				if l.current.Kind() != token.Delimiter {
					l.err = codes.ErrInvalidToken
					writeback(i + 1)

					return
				}
				if l.current.Delimiter().IsClosing() {
					l.err = codes.ErrMissingComma
					writeback(i + 1)

					return
				}
				if l.isInArray() {
					if l.current.Delimiter() != token.OpeningSquareBracket &&
						l.current.Delimiter() != token.Comma {
						l.err = codes.ErrMissingComma
						writeback(i + 1)

						return
					}
				} else if !l.current.IsColon() {
					l.err = codes.ErrMissingKey
					writeback(i + 1)

					return
				}
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}

			i++
			l.expectKey = true
			l.pushObject()
			if l.err != nil {
				writeback(i)

				return
			}
			l.current = token.MakeDelimiter(token.OpeningBracket)
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

		case openingSquareBracket:
			if l.current.IsKnown() {
				if l.current.Kind() != token.Delimiter {
					l.err = codes.ErrInvalidToken
					writeback(i + 1)

					return
				}
				if l.current.Delimiter().IsClosing() {
					l.err = codes.ErrMissingComma
					writeback(i + 1)

					return
				}
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}

			i++
			l.pushArray()
			if l.err != nil {
				writeback(i)

				return
			}
			l.current = token.MakeDelimiter(token.OpeningSquareBracket)
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				writeback(i)

				return
			}

		case doubleQuote:
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return
			}

			writeback(i + 1)
			l.current = l.consumeString()
			if l.err != nil {
				return
			}
			i = l.consumed
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				return
			}

		case startOfTrue, startOfFalse:
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}

			writeback(i + 1)
			l.current = l.consumeBoolean(b)
			if l.err != nil {
				return
			}
			i = l.consumed
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				return
			}

		case minusSign, decimalPoint, '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}

			numStart := i
			runFrom := i + 1
			var firstDigit byte
			ok := true

			switch {
			case b >= '0' && b <= '9':
				firstDigit = b
			case b == minusSign:
				if uint(i+1) < uint(len(data)) && data[i+1] >= '0' && data[i+1] <= '9' {
					firstDigit = data[i+1]
					runFrom = i + 2
				} else {
					ok = false
				}
			default: // decimalPoint
				ok = false
			}

			if ok {
				n := runFrom
				for uint(n) < uint(len(data)) && '0' <= data[n] && data[n] <= '9' {
					n++
				}

				leadingZero := firstDigit == '0' && n > runFrom
				end := n
				var term byte
				if uint(end) < uint(len(data)) {
					term = data[end]
				}
				// extend the fast path over a fractional part ('.' 1*DIGIT). A
				// trailing dot (no fraction digit) leaves term==decimalPoint, which the
				// final guard routes to consumeNumberWhole for the right error.
				if !leadingZero && term == decimalPoint {
					m := end + 1
					for uint(m) < uint(len(data)) && '0' <= data[m] && data[m] <= '9' {
						m++
					}
					if m > end+1 { // at least one fractional digit
						end = m
						term = 0
						if uint(end) < uint(len(data)) {
							term = data[end]
						}
					}
				}
				// extend over an exponent ((e|E) [+|-] 1*DIGIT). Completing it inline
				// is cheaper than bailing to consumeNumberWhole, which would re-scan
				// the int+frac we already consumed. A malformed exponent leaves
				// term=='e'/'E' and routes to the slow path for the right error.
				if !leadingZero && (term == 'e' || term == 'E') {
					m := end + 1
					if uint(m) < uint(len(data)) && (data[m] == '+' || data[m] == '-') {
						m++
					}
					expStart := m
					for uint(m) < uint(len(data)) && '0' <= data[m] && data[m] <= '9' {
						m++
					}
					if m > expStart { // at least one exponent digit
						end = m
						term = 0
						if uint(end) < uint(len(data)) {
							term = data[end]
						}
					}
				}

				if !leadingZero && term != decimalPoint && term != 'e' && term != 'E' {
					l.current = token.MakeWithValue(token.Number, data[numStart:end:end])
					i = end
					writeback(end)
					blankStart = i // this path continues, bypassing the loop-bottom update
					if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
						return
					}

					continue
				}
			}

			writeback(i + 1)
			l.current = l.consumeNumberWhole(b)
			if l.err != nil {
				return
			}
			i = l.consumed
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				return
			}

		case startOfNull:
			if l.current.IsKnown() && !l.current.Delimiter().AcceptValue() {
				l.err = codes.ErrDelimitedValue
				l.current = token.None
				writeback(i + 1)

				return
			}
			if l.expectKey {
				l.err = codes.ErrMissingKey
				writeback(i + 1)

				return
			}

			writeback(i + 1)
			l.current = l.consumeNull(b)
			if l.err != nil {
				return
			}
			i = l.consumed
			if !yield(p.emit(l.current, blanks, l.tokLine, l.tokCol)) {
				return
			}

		default:
			l.err = codes.ErrInvalidToken
			writeback(i + 1)

			return
		}

		// the token just processed ends at i: the next blanks run starts here.
		// (the afterKey colon path updates blankStart itself before its continue.)
		blankStart = i
	}

	writeback(i)
	// classify the terminal EOF for its side effects on l.err/l.isAtEOF; the
	// push core yields no token here, so the returned EOF token is discarded.
	_ = errCheckState(l, p, io.EOF)
}

// errCheckState is generated by lexgen from errCheckG; DO NOT EDIT
// (edit errCheckG in generic.go, then re-run go generate).
//
//nolint:gocognit,gocyclo
func errCheckState(l *L, p statePolicy, err error) token.T {
	hadToken := l.current.IsKnown()
	l.current = token.None

	if errors.Is(err, io.EOF) {
		switch {
		case l.isInContainer():
			if l.isInObject() {
				l.err = codes.ErrNotInObject
			} else {
				l.err = codes.ErrNotInArray
			}
		case l.isAtEOF:
			l.err = io.EOF
		case !hadToken:
			l.err = codes.ErrNoData
		}

		l.isAtEOF = true

		return p.eof(l.blanks)
	}

	l.err = err

	return p.none()
}
