package model

import (
	"slices"

	"github.com/fredbi/core/jsonschema/analyzers"
)

// TargetModel holds the data model for templates generating models.
//
// There is one [TargetModel] structure per generated target file.
//
// A single [TargetModel] contains one or several [TargetSchema] to be generated in the same file.
type TargetModel struct {
	GenModelOptions
	TargetCodeFlags // kind of target file
	LocationInfo    // file, path, package info

	ID             analyzers.UniqueID // unique ID for this model, e.g. a UUID
	Name           string             // original name (from the spec, if any), e.g. "model"
	RelatedParent  analyzers.UniqueID // marks that a type, originally an anonymous schema and with an autogenerated type, has its parent there
	UltimateParent analyzers.UniqueID // marks that a type, should be merged as a schema of this root
	StdImports     ImportsMap         // imports from the standard library
	Imports        ImportsMap         // non-standard imports
	Schemas        []TargetSchema     // all the schemas (i.e. go types) to produce in a single source model file
}

func (m *TargetModel) MergeSchemas(from []TargetSchema) {
	m.Schemas = slices.Concat(m.Schemas, from) // TODO: should reorder
}

type GenModelOptions struct {
	*GenOptions
}
