// Code generated by command: go run asm.go -out stringstop_amd64.s -stubs stub_amd64.go -pkg simd. DO NOT EDIT.

package simd

// stringStopIndexAVX2 returns the index of the first byte that is < 0x20, '"' (0x22) or '\' (0x5c), or len(data) if none. AVX2, 32 bytes/iter.
func stringStopIndexAVX2(data []byte) int
